/* Kamisato Estate service worker — generated by scripts/make-sw.mjs. Do not edit. */
'use strict'
const CACHE = "ayaka-c600189-2026-09-19T11-27-49-863Z-web"
// Not stamped, and kept across activations on purpose: these files keep their
// names from build to build, so a deploy must not evict them. Bump the version
// only to force every visitor to re-fetch this half.
const RUNTIME = "ayaka-runtime-v1"
const SHELL = [
  "./",
  "./index.html",
  "./fonts.css",
  "./fonts/inter-latin-400.woff2",
  "./fonts/inter-latin-500.woff2",
  "./fonts/inter-latin-700.woff2",
  "./fonts/noto-serif-jp-latin-400.woff2",
  "./fonts/noto-sans-jp-latin-400.woff2",
  "./favicon.svg",
  "./apple-touch-icon.png",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-maskable-512.png",
  "./manifest.webmanifest",
  "./snapshot/fx.json",
  "./snapshot/geo.json",
  "./snapshot/manifest.json",
  "./snapshot/status.json",
  "./snapshot/stocks.json",
  "./snapshot/weather.json",
  "./assets/index-Cp8htQcj.js",
  "./assets/rolldown-runtime-hePW80VL.js",
  "./assets/react-CbYonmBs.js",
  "./assets/lag-guard-DCZE-gKX.js",
  "./assets/keys-CCpukQ-l.js",
  "./assets/prefs-BgN5oRxX.js",
  "./assets/deck-lang-BV3W_RRz.js",
  "./assets/build-info-D7h5aYx1.js",
  "./assets/tea-seal-BuWgiNGZ.js",
  "./assets/speak-DiNS5kI9.js",
  "./assets/index-CmnVy3_D.css",
  "./assets/ayaka-room-B3yohL4S.css",
  "./assets/ayaka-room-Cy_SgzTj.js",
  "./assets/bible-reader-DsgbQQpw.js",
  "./assets/bible-reader-OCCOk5I2.css",
  "./assets/courtyard-BM5q5hxP.css",
  "./assets/courtyard-De9lLjtk.js",
  "./assets/estate-map-CW2T-qAa.js",
  "./assets/estate-map-KqTLU-le.css"
]
// The same list, asked the way the fetch handler asks it. Shell membership is
// tested on every request the worker sees, and an array answers by walking
// itself: with the room chunks precached the list is long enough that the walk
// is the first thing a navigation pays for. The array stays — the install loop
// reads it in order, and order is what makes a precache legible.
const SHELL_SET = new Set(SHELL)
// Paths served stale-while-revalidate: same names across builds, so refresh behind the cache.
const STALE_OK = /^\.\/(fonts|estate|bible|koi|quotes|assistants|voice)\//
// The sealed tea room's own files, which sit at the root rather than in a
// directory of their own and so match no prefix above: eight encrypted hero
// pictures, the seal's key file and the portrait, 14 MB in all. Without a rule
// a visitor who installed the estate downloaded the whole room and still met a
// lock that could not open without a network. Stale-while-revalidate out of
// RUNTIME, never precached — 14 MB on install is not an install.
const TEA_OK = /^\.\/(ayaka-tea-hero[^/]*\.jpg\.enc|tea-seal\.json|ayaka-portrait\.jpg)$/
// Everything the runtime cache holds, and therefore everything the trim measures.
function runtimeOk(rel) {
  return STALE_OK.test(rel) || TEA_OK.test(rel)
}
// Paths never cached: the estate's own live endpoints, which must not go stale.
const LIVE = /^\.\/api\//
// The bundled captures: network first (they may be re-captured between builds),
// but answered from the precache when the network is not there at all.
const SNAPSHOT = /^\.\/snapshot\//
// A navigation waits this long for the network before the precached shell answers.
const NAV_PATIENCE_MS = 3000
// How many revalidated files the cache keeps. The paintings and the 66 tea
// clips are megabytes each; without a ceiling the cache grows for ever.
const STALE_CAP = 240
// And how many *bytes* it keeps. A count alone is not a ceiling: 240 entries of
// paintings and tea clips is hundreds of megabytes on a visitor's device, which
// is not a cache, it is a download. Sizes come from the cached responses'
// own `content-length`; an entry that does not declare one is assumed to be
// this many bytes rather than free, so an unlabelled file cannot hide.
const STALE_BYTE_CAP = 120 * 1024 * 1024
const ASSUMED_BYTES = 256 * 1024
const TRIM_EVERY_MS = 30000
// How many cached entries a trim measures at once. One await per slice instead
// of one per entry; small enough that a deep cache is not read whole.
const TRIM_SLICE = 24
let trimmedAt = 0
// What the device has actually granted. STALE_BYTE_CAP above is the estate's
// own ceiling and it is a fixed number on every device: a phone with a gigabyte
// left and a phone with forty megabytes left were both told to keep 120 MB of
// paintings and tea clips. The browser answers that by evicting the origin's
// storage whole — which costs the visitor the precached shell, the record book
// and the saved games at once, and offline costs them the estate. The cache
// therefore keeps half of what the device says it may have, or the estate's own
// ceiling, whichever is the smaller.
//
// Read once per worker life, off the fetch path: `estimate()` is a round trip
// and a quota does not move while a worker is alive. Where it does not exist —
// Safari before 17, a private window — the constant stands, as it did.
let grantedCap = 0
async function byteCap() {
  if (grantedCap) return grantedCap
  grantedCap = STALE_BYTE_CAP
  try {
    const store = navigator.storage
    if (store && typeof store.estimate === 'function') {
      const quota = Number((await store.estimate()).quota)
      if (Number.isFinite(quota) && quota > 0) grantedCap = Math.min(STALE_BYTE_CAP, Math.floor(quota / 2))
    }
  } catch {
    // An estimate that throws is no grant at all: the estate's own ceiling stands.
  }
  return grantedCap
}

// A precache miss must not kill the install.
//
// `addAll` is one transaction: a single 404, a redirect, or one file a proxy
// or an extension refuses rejects the whole thing, and the worker never
// installs at all — so an estate that would have worked offline apart from one
// missing icon works offline not at all, and silently, because nothing on the
// page ever learns the install failed. Each URL is added on its own, what fails
// is counted and named in the console, and the shell that did arrive is kept.
// `verify:build` still holds every SHELL entry to a real file on disk, so a
// miss here is a fault worth reading about, not a state to tolerate quietly.
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    const missed = []
    for (const url of SHELL) {
      try {
        await cache.add(url)
      } catch {
        missed.push(url)
      }
    }
    if (missed.length && typeof console !== 'undefined') {
      console.warn('[ayaka] ' + missed.length + ' of ' + SHELL.length + ' precache entries did not arrive: ' + missed.join(', '))
    }
  })())
})

// A new worker waits instead of taking over a tab that is already open: swapping
// the shell under a visitor mid-session serves them half of one build and half of
// the next. The page offers a reload and posts this message when it is taken.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // The browser may start the navigation request while the worker is still
    // booting, so a cold start costs nothing.
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable().catch(() => {})
    }
    const keys = await caches.keys()
    // Only the estate's own caches. caches.keys() is origin-wide, and the other
    // projects published on this host keep their caches in the same place.
    const mine = keys.filter((k) => k.startsWith('ayaka-') && k !== CACHE && k !== RUNTIME)
    await Promise.all(mine.map((k) => caches.delete(k)))
    await self.clients.claim()
  })())
})

// The path of a request relative to the worker's own directory, as "./x/y".
function relative(url) {
  const base = new URL('./', self.location.href)
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return null
  return './' + url.pathname.slice(base.pathname.length)
}

// Read from this cache by name, never the origin-wide caches.match: a hashed
// name from another project on the same host could answer for one of ours.
async function cacheFirst(req) {
  const cache = await caches.open(CACHE)
  const hit = await cache.match(req)
  if (hit) return hit
  const res = await fetch(req)
  if (res.ok) cache.put(req, res.clone()).catch(() => {})
  return res
}

// The bundled captures: the network's answer is always preferred, and the
// precached copy stands in when there is no network or the host answers badly.
// This is what makes `?offline=1` true offline rather than "offline, provided
// the network is up".
async function freshFirst(req) {
  const cache = await caches.open(CACHE)
  try {
    const res = await fetch(req)
    if (res && res.ok) {
      cache.put(req, res.clone()).catch(() => {})
      return res
    }
    const hit = await cache.match(req)
    return hit || res
  } catch (err) {
    const hit = await cache.match(req)
    if (hit) return hit
    throw err
  }
}

// A metered or very slow connection pays for every background refresh, so on one
// the cached copy answers alone and nothing is fetched behind it.
function thrifty() {
  const link = navigator.connection
  if (!link) return false
  return Boolean(link.saveData) || link.effectiveType === 'slow-2g' || link.effectiveType === '2g'
}

// Keeps the runtime cache under STALE_CAP entries, oldest first
// (cache.keys() answers in insertion order). Throttled, and always off the path
// the visitor is waiting on.
async function trim(cache) {
  const now = Date.now()
  if (now - trimmedAt < TRIM_EVERY_MS) return
  // Stamped before the first await, so the trims a burst of puts asks for are
  // one trim and not a queue of them.
  trimmedAt = now
  const [cap, keys] = await Promise.all([byteCap(), cache.keys()])
  const stale = keys.filter((r) => {
    const rel = relative(new URL(r.url))
    return rel !== null && runtimeOk(rel)
  })
  if (stale.length <= 1) return
  // Newest first, keeping entries until either ceiling is reached; everything
  // older than the cut is dropped. One entry always survives, however large it
  // declares itself, so a single oversized file cannot empty the cache.
  //
  // The sizes are read a sliceful at a time rather than one entry after
  // another: `cache.match` is a storage round trip, and awaiting up to
  // STALE_CAP of them in a row made a trim as long as the cache is deep. A
  // slice is one await for TRIM_SLICE lookups, the walk inside it is still
  // newest-first and stops at the same entry the sequential walk stopped at,
  // and the ceilings are reached within a slice of where they were before —
  // so at most TRIM_SLICE-1 lookups are paid for and not used.
  let bytes = 0
  let keep = 0
  let full = false
  for (let end = stale.length; end > 0 && keep < STALE_CAP && !full; end -= TRIM_SLICE) {
    const start = Math.max(0, end - TRIM_SLICE)
    const hits = await Promise.all(stale.slice(start, end).map((r) => cache.match(r)))
    for (let i = hits.length - 1; i >= 0 && keep < STALE_CAP; i -= 1) {
      const hit = hits[i]
      const declared = hit && hit.headers ? Number(hit.headers.get('content-length')) : 0
      const size = Number.isFinite(declared) && declared > 0 ? declared : ASSUMED_BYTES
      if (keep > 0 && bytes + size > cap) {
        full = true
        break
      }
      bytes += size
      keep += 1
    }
  }
  if (keep >= stale.length) return
  await Promise.all(stale.slice(0, stale.length - keep).map((r) => cache.delete(r)))
}

// `which` is RUNTIME for the name-stable files and CACHE for the few shell
// entries that are not hashed (`fonts.css`, the manifest, the favicon): those
// were precached with this build and must still answer offline from it.
//
// `opts` is handed straight to `cache.match`. The sealed tea files are asked for
// with a `?b=<commit>` stamp (`src/lib/tea-seal.ts`), so a stamped ask after a
// deploy would miss a perfectly good cached copy — and store a second one beside
// it — unless the lookup ignores the query. Nothing else here needs that: the
// rest of the runtime half is asked for by bare path.
async function staleWhileRevalidate(req, which, opts) {
  const cache = await caches.open(which)
  const hit = await cache.match(req, opts)
  if (hit && thrifty()) return hit
  // Stored under a name with the query stripped whenever the lookup ignores it:
  // otherwise every deploy's stamp would leave another copy of a 2 MB picture
  // beside the last one, and the trim would spend the whole ceiling on one room.
  const key = opts && opts.ignoreSearch ? new URL(req.url).origin + new URL(req.url).pathname : req
  const refresh = fetch(req).then((res) => {
    if (res.ok) cache.put(key, res.clone()).then(() => (which === RUNTIME ? trim(cache) : undefined)).catch(() => {})
    return res
  })
  if (hit) {
    refresh.catch(() => {})
    return hit
  }
  return refresh
}

async function shellFirst(event) {
  const cache = await caches.open(CACHE)
  const cached = await cache.match('./index.html')
  const network = (async () => {
    const preloaded = await event.preloadResponse
    const res = preloaded || (await fetch(event.request))
    /*
      The answer is deliberately *not* written back into CACHE. CACHE is stamped
      with this build's commit and holds this build's shell, precached on
      install; within a build there is nothing about `./index.html` to refresh.
      After a deploy, though, this handler still belongs to the old worker (a new
      one waits), so the page it would store is the *new* index.html, naming
      hashed `assets/…` URLs that are in neither this cache nor, once the deploy
      settles, reachable offline. The next slow or offline navigation was then
      answered with a shell whose scripts could not be found: a blank estate,
      which is the exact half-old, half-new mixture the waiting-worker flow
      exists to prevent.
    */
    return res
  })()
  /*
    A host that answers at all can still answer badly: GitHub Pages hands out its
    own 404 page for a deep link into the estate. That is not the estate, so the
    precached shell answers instead whenever the response is not ok — not only
    when the fetch throws.
  */
  const answer = network
    .then((res) => ((res && res.ok) || !cached ? res : cached))
    .catch((err) => {
      if (cached) return cached
      throw err
    })
  if (!cached) return answer
  /*
    And a captive portal answers neither way: it holds the connection open and
    the navigation hangs on a blank tab. The shell is on disk, so after
    NAV_PATIENCE_MS it is served and the estate opens.
  */
  let timer = 0
  const patience = new Promise((resolve) => {
    timer = setTimeout(() => resolve(cached), NAV_PATIENCE_MS)
  })
  return Promise.race([answer, patience]).finally(() => clearTimeout(timer))
}

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  const rel = relative(url)
  if (rel === null) return
  if (LIVE.test(rel)) return
  if (SNAPSHOT.test(rel)) {
    event.respondWith(freshFirst(req))
    return
  }
  if (req.mode === 'navigate') {
    event.respondWith(shellFirst(event))
    return
  }
  if (rel.startsWith('./assets/')) {
    event.respondWith(cacheFirst(req))
    return
  }
  // Shell membership is asked first. The two tests overlap — `./fonts/` is a
  // STALE_OK prefix and the precached `fonts.css` and its woff2 sit under it —
  // and STALE_OK winning meant a file that was *put in this build's cache at
  // install* was looked for in the runtime cache instead, which offline is
  // empty on a first paint. The estate then opened in a fallback face. What was
  // precached answers from where it was precached.
  if (SHELL_SET.has(rel)) {
    event.respondWith(staleWhileRevalidate(req, CACHE))
    return
  }
  if (STALE_OK.test(rel)) {
    event.respondWith(staleWhileRevalidate(req, RUNTIME))
    return
  }
  if (TEA_OK.test(rel)) {
    event.respondWith(staleWhileRevalidate(req, RUNTIME, { ignoreSearch: true }))
  }
})
