/* Kamisato Estate service worker — generated by scripts/make-sw.mjs. Do not edit. */
'use strict'
const CACHE = "ayaka-6c58e7b-2026-09-26T13-08-41-027Z-web"
// Not stamped, and kept across activations on purpose: these files keep their
// names from build to build, so a deploy must not evict them. Bump the version
// only to force every visitor to re-fetch this half.
const RUNTIME = "ayaka-runtime-v1"
// Both names above are *unscoped build identities*. The caches this worker opens
// are namespaced by the deployment it was served from, because CacheStorage is
// keyed by origin and this origin carries two deployments of the estate at two
// paths; without the namespace each one's activation swept the other's shell
// away and both shared one runtime cache.
function scopeKey(pathname) {
  const dir = String(pathname == null ? '/' : pathname).replace(/[^/]*$/, '')
  const key = dir.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  return key || 'root'
}
function ownedPrefix(pathname) {
  return 'ayaka-' + scopeKey(pathname) + '~'
}
function scopedCacheName(base, pathname) {
  const rest = base.indexOf('ayaka-') === 0 ? base.slice(6) : base
  return ownedPrefix(pathname) + rest
}
// The worker's own directory — the deployment it was copied into. `base: './'`
// means one built artefact serves every path, so this is only knowable here.
const SCOPE_PATH = new URL('./', self.location.href).pathname
const OWNED = ownedPrefix(SCOPE_PATH)
const SHELL_STORE = scopedCacheName(CACHE, SCOPE_PATH)
const RUNTIME_STORE = scopedCacheName(RUNTIME, SCOPE_PATH)
const SHELL = [
  "./",
  "./index.html",
  "./estate-story-20260926.json",
  "./estate-story-20260926.zh.json",
  "./estate-story-20260926.ja.json",
  "./credits/kellen-one-of-one-20260926.png",
  "./fonts.css",
  "./fonts/inter-latin-400.woff2",
  "./fonts/inter-latin-500.woff2",
  "./fonts/inter-latin-700.woff2",
  "./fonts/noto-serif-jp-latin-400.woff2",
  "./fonts/noto-sans-jp-latin-400.woff2",
  "./favicon.svg",
  "./apple-touch-icon.png",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-maskable-512.png",
  "./manifest.webmanifest",
  "./snapshot/fx.json",
  "./snapshot/geo.json",
  "./snapshot/manifest.json",
  "./snapshot/status.json",
  "./snapshot/stocks.json",
  "./snapshot/weather.json",
  "./assets/index-CjsayjPt.js",
  "./assets/rolldown-runtime-hePW80VL.js",
  "./assets/react-D0Ec-185.js",
  "./assets/lag-guard-yIpEkFVY.js",
  "./assets/use-fx-tier-StgUkCqr.js",
  "./assets/storage-DYFzANnb.js",
  "./assets/prefs-BPoxcaQn.js",
  "./assets/scores-BEDcyZYL.js",
  "./assets/deck-lang-6TOyiWud.js",
  "./assets/build-info-DG4cfbO5.js",
  "./assets/tea-seal-COZ5mExb.js",
  "./assets/speak-CEiZPNtK.js",
  "./assets/chunk-error-DrufujkD.js",
  "./assets/error-boundary-Ci85kkn5.js",
  "./assets/preload-helper-HclGiUj8.js",
  "./assets/deck-Do8w3kb8.js",
  "./assets/live-AzblpAgK.js",
  "./assets/door-transition-QiEiS0Bj.js",
  "./assets/clipboard-Cx3oaGGb.js",
  "./assets/tool-lang-B5a3eNwf.js",
  "./assets/ui-DolqNgz2.js",
  "./assets/perf-trace-lIYLa8MR.js",
  "./assets/ui-mr6J6RWc.css",
  "./assets/index-D_-3VYJc.css",
  "./assets/activation-card-mOnmiCuB.js",
  "./assets/add-deadline-DbsZTpCU.js",
  "./assets/ai-autofill-B_mp1xOP.js",
  "./assets/ai-local-D0xTTMKG.js",
  "./assets/ai-panel-BSDXT1D0.js",
  "./assets/answer-VDXExc_Z.js",
  "./assets/automations-Bkix5lIb.js",
  "./assets/automations-CJkNTTVh.css",
  "./assets/automations-DZi7FqqV.js",
  "./assets/avatars-BMFh_baf.js",
  "./assets/ayaka-room-Bp0tC3Ld.css",
  "./assets/ayaka-room-CGmT1vNb.js",
  "./assets/backup-card-DbmYV60R.js",
  "./assets/bayes-card-ATkTddFI.js",
  "./assets/bible-reader-B2Bgwvso.css",
  "./assets/bible-reader-YecYfoBo.js",
  "./assets/c41-rooms-BTwYH3Tk.css",
  "./assets/calendar-ics-DIjYsXd4.js",
  "./assets/calendar-time-DXrCO0k9.js",
  "./assets/calendar-view-vDROWNMy.js",
  "./assets/card-rows-C_ZiQM8v.js",
  "./assets/chess-go-B7uywM2n.js",
  "./assets/chess-go-CRWQTFh7.css",
  "./assets/code-fx-CK2ft9k3.css",
  "./assets/code-fx-D1G70nmI.js",
  "./assets/complexity-card-FmLU6fte.js",
  "./assets/continue-CD1qritO.js",
  "./assets/continue-card-69wvMF8p.js",
  "./assets/corner-bl-DOalGHkc.svg",
  "./assets/corner-br-DECtH2Cd.svg",
  "./assets/corner-tl-BzMy2ihH.svg",
  "./assets/corner-tr-DWuKURBq.svg",
  "./assets/countdown-card--miApOg_.js",
  "./assets/courtyard-BIDlG1Hv.js",
  "./assets/courtyard-BRoYi_Z8.css",
  "./assets/credits-archive-BpPUesO1.js",
  "./assets/db-factories-D4_a8D3C.js",
  "./assets/db-lazy-BCONeITB.js",
  "./assets/dex-Dth2ccd0.js",
  "./assets/draft-settle-QIt9IKkG.js",
  "./assets/draft-tasks-Bu9CPtvH.js",
  "./assets/draft-tasks-card-Srhxlfxb.js",
  "./assets/draft-ui-C0ly5oLT.js",
  "./assets/edition-YTLr8LhD.js",
  "./assets/editor-DPpdMpUO.js",
  "./assets/editor-seams-3K5utKuI.js",
  "./assets/emoji-data-DCBrgNYL.js",
  "./assets/estate-assistant-Czgha5KS.js",
  "./assets/estate-assistant-wutyUkrt.css",
  "./assets/estate-credits-BiaJQaaK.js",
  "./assets/estate-credits-DdBF16e4.css",
  "./assets/estate-map-B05bqnGi.js",
  "./assets/estate-map-z8gv9Bjw.css",
  "./assets/estate-settings-CFVjCZkl.js",
  "./assets/estate-settings-kAuM6WRT.css",
  "./assets/estate-weather-BG-yqnjX.js",
  "./assets/estate-weather-CQqcHEw3.css",
  "./assets/fish-z8KNEuPh.js",
  "./assets/flashcards-card-pinYZB_c.js",
  "./assets/focus-timer-MFK21FL8.js",
  "./assets/formula-card-DJUtlsGh.js",
  "./assets/game-BGAOWFfn.js",
  "./assets/game-Bbxc0lLb.js",
  "./assets/game-BrVfwa4j.css",
  "./assets/game-BsKtfcYb.css",
  "./assets/game-Bys-duo5.css",
  "./assets/game-CrZIhJYa.js",
  "./assets/game-D00680p6.css",
  "./assets/game-DS7ZDBGs.css",
  "./assets/game-Dhw_-iPP.css",
  "./assets/game-Dj-fWfTs.css",
  "./assets/game-DkcKpxm7.css",
  "./assets/game-DuH5Lyzt.js",
  "./assets/game-KMoRZ8va.js",
  "./assets/game-gesture-L5ZIxnGa.js",
  "./assets/game-iY380dRT.js",
  "./assets/game-pause-button-CxXSPmCn.js",
  "./assets/game-s3n-KVW0.js",
  "./assets/game-sound-DcnpFX66.js",
  "./assets/game-sound-switch-rcZ_OIg2.js",
  "./assets/game-sydEwQ9e.js",
  "./assets/garden-card-DhhPW3Xo.js",
  "./assets/gloss-Catf2NUP.js",
  "./assets/gpa-card-DRTEJI0N.js",
  "./assets/handbook-CrVF-J3X.css",
  "./assets/handbook-bTGcqGh4.js",
  "./assets/handbook-content-CiKbGrTO.js",
  "./assets/heron-room-B_jCJ6bl.js",
  "./assets/heron-room-Cma26Hnr.css",
  "./assets/history-store-BtO88Knj.js",
  "./assets/home-layout-D4fSCOdC.js",
  "./assets/home-layout-panel-BkXxeNh-.js",
  "./assets/icon-U1m5ug7p.js",
  "./assets/import-export-CvN8K_Bz.js",
  "./assets/lazy-cell-CyWtL0ps.js",
  "./assets/library-CGXJJszB.js",
  "./assets/markdown-Co_25zR9.js",
  "./assets/markdown-html-lvQBlYE2.js",
  "./assets/matcha-BQGIQBzP.js",
  "./assets/matrix-card-COgj4C1n.js",
  "./assets/media-store-DRMDL9nQ.js",
  "./assets/media-view-BdldwLzR.css",
  "./assets/media-view-INmFjowT.js",
  "./assets/menu-solo-1JnstouE.js",
  "./assets/menus-CZ6KCEy9.js",
  "./assets/menus-D2p0OxEg.css",
  "./assets/metrics-card-D991NOTR.js",
  "./assets/model-CxrluwXE.js",
  "./assets/notion-card-DSx2siDx.js",
  "./assets/notion-port-C67t6Z1f.js",
  "./assets/notion-selbar-CdSZMSr9.css",
  "./assets/offline-readiness-card-D8A-mVHw.js",
  "./assets/page-chrome-CIhMmWK2.css",
  "./assets/page-chrome-HVsQs4Hy.js",
  "./assets/page-hU7-Ck0p.js",
  "./assets/pause-signal-DK6I0Bec.js",
  "./assets/peerjs-default-Bfq4GYW0.js",
  "./assets/perform-CaanBzL1.js",
  "./assets/personas-Cu-6h8m7.js",
  "./assets/phrase-browser-CXMHBiWP.css",
  "./assets/phrase-browser-CqFUMNZk.js",
  "./assets/phrasebook-CJk87Wt9.js",
  "./assets/plot-Dx-sCkoO.js",
  "./assets/postcards-panel-Dl0FNwOk.js",
  "./assets/prompts-card-BnDcDkHj.js",
  "./assets/proposal-D2NsOqzr.js",
  "./assets/provider-CvfoQHlK.js",
  "./assets/quote-wall-Cx3bEu-3.js",
  "./assets/quotes-Bwq_e4VU.js",
  "./assets/readiness-state-C6gfPozF.js",
  "./assets/reading-card-mQzxmkqy.js",
  "./assets/record-book-DzEFu_2G.js",
  "./assets/record-names-CRxmEsV2.js",
  "./assets/records-DZQBI0mE.js",
  "./assets/reel-panel-C44ktcut.js",
  "./assets/reference-drawer-C7gHkabl.css",
  "./assets/reference-drawer-wXVB7QTh.js",
  "./assets/refused-DrTrRDgF.js",
  "./assets/registry-DmftBokO.js",
  "./assets/remind-BYQiGPSw.js",
  "./assets/rich-text-BP8HnxI4.js",
  "./assets/room-53gKqsnV.css",
  "./assets/room-C3GGTW_W.js",
  "./assets/room-names-BTdJ627i.js",
  "./assets/sakura-DAjbPtq1.js",
  "./assets/schedule-card-BMxeattG.js",
  "./assets/select-DBXur7UO.js",
  "./assets/selection-bar-CbrCxxk4.js",
  "./assets/settings-geo-mTyOboJ6.js",
  "./assets/shell-ops-BSU7BN5C.js",
  "./assets/shell-tools-BD7_BXKG.css",
  "./assets/shell-tools-Ulbkaxjp.js",
  "./assets/store-5Vg7Epxb.js",
  "./assets/strings-CkNwCyfv.js",
  "./assets/study-BbQ7BA48.js",
  "./assets/syllabus-card-VZ5e0mQw.js",
  "./assets/tab-lease-banner-DrSyVkHl.js",
  "./assets/table-head-EnrujV-H.js",
  "./assets/taught-R-qjH1q5.js",
  "./assets/tea-brewing-CWh7PZN_.js",
  "./assets/tea-brewing-CXBxpqY9.css",
  "./assets/tea-chess-DPqSqVjF.js",
  "./assets/tea-go-HgJaiH7K.js",
  "./assets/tea-konpira-CKjNLK1u.js",
  "./assets/tea-konpira-DSB_PD7R.css",
  "./assets/tea-matcha-B63GFvUI.js",
  "./assets/tea-matcha-w__4TAJS.css",
  "./assets/tensor-card-DkprFZVd.js",
  "./assets/tetris-keys-CQgaRcG_.js",
  "./assets/today-BjE7GQci.js",
  "./assets/together-C894xXFJ.css",
  "./assets/together-Db3FOESn.js",
  "./assets/token-cost-card-D7qo6Lwi.js",
  "./assets/travel-pack-C0HT1ru9.js",
  "./assets/undo-DKCotAFN.js",
  "./assets/units-card-mCls1ICQ.js",
  "./assets/use-live-game-CiggmBID.js",
  "./assets/use-painted-DSFLHKBJ.js",
  "./assets/use-soft-close-BkDlP_Vm.js",
  "./assets/view-config-DBup4Xlb.js",
  "./assets/vine-h-D2f8jPMT.svg",
  "./assets/vine-v-Bwo7kXQE.svg",
  "./assets/vram-card-BnFxP5PM.js",
  "./assets/wallpaper-B4GZftJM.js",
  "./assets/webllm-provider-C2VuX2R8.js",
  "./assets/windchime-garden-B_gc8-0s.css",
  "./assets/windchime-garden-D-xANdJJ.js",
  "./assets/workspace-db-BZN-rRgQ.js",
  "./assets/workspace-db-NQnF5goz.css",
  "./assets/zipread-hKXo5VQJ.js",
  "./art/catch/basket-catching.svg",
  "./art/catch/basket-idle.svg",
  "./art/catch/basket-miss.svg",
  "./art/catch/bloom.svg",
  "./art/catch/courtyard-day-1920w.webp",
  "./art/catch/danger-snow.svg",
  "./art/catch/gold.svg",
  "./art/catch/petal-18.svg",
  "./art/catch/petal-26.svg",
  "./art/catch/petal-32.svg",
  "./art/covers/botanical-study-v1.webp",
  "./art/covers/moonlit-reflection-v1.webp",
  "./art/covers/path-to-the-peaks-v1.webp",
  "./art/covers/rainlit-archive-v2.webp",
  "./art/covers/sakura-workshop-v1.webp",
  "./art/covers/scholars-veranda-v1.webp",
  "./art/empty/draft-no-tasks.svg",
  "./art/empty/search-no-results.svg",
  "./art/empty/workspace-no-page.svg",
  "./art/map/pin-courtyard.svg",
  "./art/map/pin-door.svg",
  "./art/map/pin-hall.svg",
  "./art/map/pin-heron.svg",
  "./art/map/pin-tea.svg",
  "./art/map/pin-windchime.svg",
  "./art/map/state-here.svg",
  "./art/map/state-selected.svg",
  "./art/map/state-target.svg",
  "./art/sweeper/1.svg",
  "./art/sweeper/2.svg",
  "./art/sweeper/3.svg",
  "./art/sweeper/4.svg",
  "./art/sweeper/5.svg",
  "./art/sweeper/6.svg",
  "./art/sweeper/7.svg",
  "./art/sweeper/8.svg",
  "./art/sweeper/c.svg",
  "./art/sweeper/f.svg",
  "./art/sweeper/l.svg",
  "./art/sweeper/o.svg",
  "./art/sweeper/q.svg",
  "./art/sweeper/r.svg",
  "./art/sweeper/x.svg",
  "./art/tea/add-matcha.svg",
  "./art/tea/add-sencha.svg",
  "./art/tea/pour-shared.svg",
  "./art/tea/ready-matcha.svg",
  "./art/tea/ready-sencha.svg",
  "./art/tea/rest-matcha.svg",
  "./art/tea/rest-sencha.svg",
  "./art/tea/served-matcha.svg",
  "./art/tea/served-sencha.svg",
  "./art/tea/warm-shared.svg",
  "./estate/gate-morning-1920w.webp",
  "./estate/gate-afternoon-1920w.webp",
  "./estate/gate-evening-1920w.webp",
  "./estate/gate-night-1920w.webp",
  "./estate/door-morning-thumb.jpg",
  "./bible/kjv/index.json",
  "./fonts/jetbrains-mono-latin-400.woff2",
  "./fonts/jetbrains-mono-latin-600.woff2",
  "./fonts/jetbrains-mono-latin-700.woff2"
]
// The same list, asked the way the fetch handler asks it. Shell membership is
// tested on every request the worker sees, and an array answers by walking
// itself: with the room chunks precached the list is long enough that the walk
// is the first thing a navigation pays for. The array stays — the install loop
// reads it in order, and order is what makes a precache legible.
const SHELL_SET = new Set(SHELL)
// Paths served stale-while-revalidate: same names across builds, so refresh behind the cache.
const STALE_OK = /^\.\/(fonts|estate|bible|koi|art|quotes|assistants|voice)\//
// The sealed tea room's own files, which sit at the root rather than in a
// directory of their own and so match no prefix above: eight encrypted hero
// pictures, the seal's key file and the portrait, 14 MB in all. Without a rule
// a visitor who installed the estate downloaded the whole room and still met a
// lock that could not open without a network. Stale-while-revalidate out of
// RUNTIME, never precached — 14 MB on install is not an install.
const TEA_OK = /^\.\/(ayaka-tea-hero[^/]*\.webp\.enc|tea-seal\.json|ayaka-portrait\.jpg)$/
// Everything the runtime cache holds, and therefore everything the trim measures.
function runtimeOk(rel) {
  return STALE_OK.test(rel) || TEA_OK.test(rel)
}
// Paths never cached: the estate's own live endpoints, which must not go stale.
const LIVE = /^\.\/api\//
// The bundled captures: network first (they may be re-captured between builds),
// but answered from the precache when the network is not there at all.
const SNAPSHOT = /^\.\/snapshot\//
// A navigation waits this long for the network before the precached shell answers.
const NAV_PATIENCE_MS = 3000
// How many revalidated files the cache keeps. The paintings and the 66 tea
// clips are megabytes each; without a ceiling the cache grows for ever.
const STALE_CAP = 240
// And how many *bytes* it keeps. A count alone is not a ceiling: 240 entries of
// paintings and tea clips is hundreds of megabytes on a visitor's device, which
// is not a cache, it is a download. Sizes come from the cached responses'
// own `content-length`; an entry that does not declare one is assumed to be
// this many bytes rather than free, so an unlabelled file cannot hide.
const STALE_BYTE_CAP = 120 * 1024 * 1024
const ASSUMED_BYTES = 256 * 1024
const TRIM_EVERY_MS = 30000
// How many cached entries a trim measures at once. One await per slice instead
// of one per entry; small enough that a deep cache is not read whole.
const TRIM_SLICE = 24
let trimmedAt = 0
// What the device has actually granted. STALE_BYTE_CAP above is the estate's
// own ceiling and it is a fixed number on every device: a phone with a gigabyte
// left and a phone with forty megabytes left were both told to keep 120 MB of
// paintings and tea clips. The browser answers that by evicting the origin's
// storage whole — which costs the visitor the precached shell, the record book
// and the saved games at once, and offline costs them the estate. The cache
// therefore keeps half of what the device says it may have, or the estate's own
// ceiling, whichever is the smaller.
//
// Read once per worker life, off the fetch path: `estimate()` is a round trip
// and a quota does not move while a worker is alive. Where it does not exist —
// Safari before 17, a private window — the constant stands, as it did.
let grantedCap = 0
async function byteCap() {
  if (grantedCap) return grantedCap
  grantedCap = STALE_BYTE_CAP
  try {
    const store = navigator.storage
    if (store && typeof store.estimate === 'function') {
      const quota = Number((await store.estimate()).quota)
      if (Number.isFinite(quota) && quota > 0) grantedCap = Math.min(STALE_BYTE_CAP, Math.floor(quota / 2))
    }
  } catch {
    // An estimate that throws is no grant at all: the estate's own ceiling stands.
  }
  return grantedCap
}

// A precache miss must not kill the install.
//
// `addAll` is one transaction: a single 404, a redirect, or one file a proxy
// or an extension refuses rejects the whole thing, and the worker never
// installs at all — so an estate that would have worked offline apart from one
// missing icon works offline not at all, and silently, because nothing on the
// page ever learns the install failed. Each URL is added on its own, what fails
// is counted and named in the console, and the shell that did arrive is kept.
// `verify:build` still holds every SHELL entry to a real file on disk, so a
// miss here is a fault worth reading about, not a state to tolerate quietly.
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_STORE)
    const missed = []
    for (const url of SHELL) {
      try {
        await cache.add(url)
      } catch {
        missed.push(url)
      }
    }
    if (missed.length && typeof console !== 'undefined') {
      console.warn('[ayaka] ' + missed.length + ' of ' + SHELL.length + ' precache entries did not arrive: ' + missed.join(', '))
    }
  })())
})

// A new worker waits instead of taking over a tab that is already open: swapping
// the shell under a visitor mid-session serves them half of one build and half of
// the next. The page offers a reload and posts this message when it is taken.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // The browser may start the navigation request while the worker is still
    // booting, so a cold start costs nothing.
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable().catch(() => {})
    }
    const keys = await caches.keys()
    // Only *this deployment's* caches. caches.keys() is origin-wide: the other
    // projects published on this host keep their caches in the same place, and
    // so does the estate's other deployment at the other path on this very
    // origin. OWNED ends in the "~" that scopeKey can never produce, so this
    // predicate cannot reach past its own namespace.
    //
    // Legacy, un-namespaced "ayaka-…" caches written before c103a are left
    // alone rather than swept: while one path has updated and the other has
    // not, deleting them would take the offline shell out from under the
    // deployment still using them — exactly the bug being fixed. They belong to
    // no namespace, are never opened again, and are left to the quota manager.
    const mine = keys.filter((k) => k.startsWith(OWNED) && k !== SHELL_STORE && k !== RUNTIME_STORE)
    await Promise.all(mine.map((k) => caches.delete(k)))
    await self.clients.claim()
  })())
})

// The path of a request relative to the worker's own directory, as "./x/y".
function relative(url) {
  const base = new URL('./', self.location.href)
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return null
  return './' + url.pathname.slice(base.pathname.length)
}

// Read from this cache by name, never the origin-wide caches.match: a hashed
// name from another project on the same host could answer for one of ours.
async function cacheFirst(req) {
  const cache = await caches.open(SHELL_STORE)
  const hit = await cache.match(req)
  if (hit) return hit
  const res = await fetch(req)
  if (res.ok) cache.put(req, res.clone()).catch(() => {})
  return res
}

// The bundled captures: the network's answer is always preferred, and the
// precached copy stands in when there is no network or the host answers badly.
// This is what makes `?offline=1` true offline rather than "offline, provided
// the network is up".
async function freshFirst(req) {
  const cache = await caches.open(SHELL_STORE)
  try {
    const res = await fetch(req)
    if (res && res.ok) {
      cache.put(req, res.clone()).catch(() => {})
      return res
    }
    const hit = await cache.match(req)
    return hit || res
  } catch (err) {
    const hit = await cache.match(req)
    if (hit) return hit
    throw err
  }
}

// A metered or very slow connection pays for every background refresh, so on one
// the cached copy answers alone and nothing is fetched behind it.
function thrifty() {
  const link = navigator.connection
  if (!link) return false
  return Boolean(link.saveData) || link.effectiveType === 'slow-2g' || link.effectiveType === '2g'
}

// Keeps the runtime cache under STALE_CAP entries, oldest first
// (cache.keys() answers in insertion order). Throttled, and always off the path
// the visitor is waiting on.
async function trim(cache) {
  const now = Date.now()
  if (now - trimmedAt < TRIM_EVERY_MS) return
  // Stamped before the first await, so the trims a burst of puts asks for are
  // one trim and not a queue of them.
  trimmedAt = now
  const [cap, keys] = await Promise.all([byteCap(), cache.keys()])
  const stale = keys.filter((r) => {
    const rel = relative(new URL(r.url))
    return rel !== null && runtimeOk(rel)
  })
  if (stale.length <= 1) return
  // Newest first, keeping entries until either ceiling is reached; everything
  // older than the cut is dropped. One entry always survives, however large it
  // declares itself, so a single oversized file cannot empty the cache.
  //
  // The sizes are read a sliceful at a time rather than one entry after
  // another: `cache.match` is a storage round trip, and awaiting up to
  // STALE_CAP of them in a row made a trim as long as the cache is deep. A
  // slice is one await for TRIM_SLICE lookups, the walk inside it is still
  // newest-first and stops at the same entry the sequential walk stopped at,
  // and the ceilings are reached within a slice of where they were before —
  // so at most TRIM_SLICE-1 lookups are paid for and not used.
  let bytes = 0
  let keep = 0
  let full = false
  for (let end = stale.length; end > 0 && keep < STALE_CAP && !full; end -= TRIM_SLICE) {
    const start = Math.max(0, end - TRIM_SLICE)
    const hits = await Promise.all(stale.slice(start, end).map((r) => cache.match(r)))
    for (let i = hits.length - 1; i >= 0 && keep < STALE_CAP; i -= 1) {
      const hit = hits[i]
      const declared = hit && hit.headers ? Number(hit.headers.get('content-length')) : 0
      const size = Number.isFinite(declared) && declared > 0 ? declared : ASSUMED_BYTES
      if (keep > 0 && bytes + size > cap) {
        full = true
        break
      }
      bytes += size
      keep += 1
    }
  }
  if (keep >= stale.length) return
  await Promise.all(stale.slice(0, stale.length - keep).map((r) => cache.delete(r)))
}

// `which` is RUNTIME_STORE for the name-stable files and SHELL_STORE for the few shell
// entries that are not hashed (`fonts.css`, the manifest, the favicon): those
// were precached with this build and must still answer offline from it.
//
// `opts` is handed straight to `cache.match`. The sealed tea files are asked for
// with a `?b=<commit>` stamp (`src/lib/tea-seal.ts`), so a stamped ask after a
// deploy would miss a perfectly good cached copy — and store a second one beside
// it — unless the lookup ignores the query. Nothing else here needs that: the
// rest of the runtime half is asked for by bare path.
async function staleWhileRevalidate(req, which, opts) {
  const cache = await caches.open(which)
  const hit = await cache.match(req, opts)
  if (hit && thrifty()) return hit
  // Stored under a name with the query stripped whenever the lookup ignores it:
  // otherwise every deploy's stamp would leave another copy of a 2 MB picture
  // beside the last one, and the trim would spend the whole ceiling on one room.
  const key = opts && opts.ignoreSearch ? new URL(req.url).origin + new URL(req.url).pathname : req
  const refresh = fetch(req).then((res) => {
    if (res.ok) cache.put(key, res.clone()).then(() => (which === RUNTIME_STORE ? trim(cache) : undefined)).catch(() => {})
    return res
  })
  if (hit) {
    refresh.catch(() => {})
    return hit
  }
  return refresh.catch(async (error) => {
    // A larger viewport can select an uncached full painting while offline.
    // Keep its exact scene/crop/format from this deployment's smaller cache;
    // never store those lower-resolution bytes under the full-size key.
    const url = new URL(req.url)
    const rel = relative(url)
    if (which === RUNTIME_STORE && /^\.\/estate\/[^/]+\.(webp|jpe?g)$/i.test(rel) && !/-\d+w\./i.test(rel)) {
      const shell = await caches.open(SHELL_STORE)
      for (const width of [1920, 1280]) {
        const rung = new URL(url.href)
        rung.pathname = rung.pathname.replace(/(\.[^.]+)$/, '-' + width + 'w$1')
        const lower = await shell.match(rung.href) || await cache.match(rung.href)
        if (lower && lower.ok) return lower
      }
    }
    throw error
  })
}

async function shellFirst(event) {
  const cache = await caches.open(SHELL_STORE)
  const cached = await cache.match('./index.html')
  const network = (async () => {
    const preloaded = await event.preloadResponse
    const res = preloaded || (await fetch(event.request))
    /*
      The answer is deliberately *not* written back into SHELL_STORE, which is stamped
      with this build's commit and holds this build's shell, precached on
      install; within a build there is nothing about `./index.html` to refresh.
      After a deploy, though, this handler still belongs to the old worker (a new
      one waits), so the page it would store is the *new* index.html, naming
      hashed `assets/…` URLs that are in neither this cache nor, once the deploy
      settles, reachable offline. The next slow or offline navigation was then
      answered with a shell whose scripts could not be found: a blank estate,
      which is the exact half-old, half-new mixture the waiting-worker flow
      exists to prevent.
    */
    return res
  })()
  /*
    A host that answers at all can still answer badly: GitHub Pages hands out its
    own 404 page for a deep link into the estate. That is not the estate, so the
    precached shell answers instead whenever the response is not ok — not only
    when the fetch throws.
  */
  const answer = network
    .then((res) => ((res && res.ok) || !cached ? res : cached))
    .catch((err) => {
      if (cached) return cached
      throw err
    })
  if (!cached) return answer
  /*
    And a captive portal answers neither way: it holds the connection open and
    the navigation hangs on a blank tab. The shell is on disk, so after
    NAV_PATIENCE_MS it is served and the estate opens.
  */
  let timer = 0
  const patience = new Promise((resolve) => {
    timer = setTimeout(() => resolve(cached), NAV_PATIENCE_MS)
  })
  return Promise.race([answer, patience]).finally(() => clearTimeout(timer))
}

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  const rel = relative(url)
  if (rel === null) return
  if (LIVE.test(rel)) return
  if (SNAPSHOT.test(rel)) {
    event.respondWith(freshFirst(req))
    return
  }
  if (req.mode === 'navigate') {
    event.respondWith(shellFirst(event))
    return
  }
  if (rel.startsWith('./assets/')) {
    event.respondWith(cacheFirst(req))
    return
  }
  // Shell membership is asked first. The two tests overlap — `./fonts/` is a
  // STALE_OK prefix and the precached `fonts.css` and its woff2 sit under it —
  // and STALE_OK winning meant a file that was *put in this build's cache at
  // install* was looked for in the runtime cache instead, which offline is
  // empty on a first paint. The estate then opened in a fallback face. What was
  // precached answers from where it was precached.
  if (SHELL_SET.has(rel)) {
    event.respondWith(staleWhileRevalidate(req, SHELL_STORE))
    return
  }
  if (STALE_OK.test(rel)) {
    event.respondWith(staleWhileRevalidate(req, RUNTIME_STORE))
    return
  }
  if (TEA_OK.test(rel)) {
    event.respondWith(staleWhileRevalidate(req, RUNTIME_STORE, { ignoreSearch: true }))
  }
})
