/* Kamisato Estate service worker — generated by scripts/make-sw.mjs. Do not edit. */
'use strict'
const CACHE = "ayaka-bc116cb-2026-10-03T19-17-23-244Z-web"
// Not stamped, and kept across activations on purpose: these files keep their
// names from build to build, so a deploy must not evict them. Bump the version
// only to force every visitor to re-fetch this half.
const RUNTIME = "ayaka-runtime-v1"
// Both names above are *unscoped build identities*. The caches this worker opens
// are namespaced by the deployment it was served from, because CacheStorage is
// keyed by origin and this origin carries two deployments of the estate at two
// paths; without the namespace each one's activation swept the other's shell
// away and both shared one runtime cache.
function scopeKey(pathname) {
  const dir = String(pathname == null ? '/' : pathname).replace(/[^/]*$/, '')
  const key = dir.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  return key || 'root'
}
function ownedPrefix(pathname) {
  return 'ayaka-' + scopeKey(pathname) + '~'
}
function scopedCacheName(base, pathname) {
  const rest = base.indexOf('ayaka-') === 0 ? base.slice(6) : base
  return ownedPrefix(pathname) + rest
}
// The worker's own directory — the deployment it was copied into. `base: './'`
// means one built artefact serves every path, so this is only knowable here.
const SCOPE_PATH = new URL('./', self.location.href).pathname
const OWNED = ownedPrefix(SCOPE_PATH)
const SHELL_STORE = scopedCacheName(CACHE, SCOPE_PATH)
const RUNTIME_STORE = scopedCacheName(RUNTIME, SCOPE_PATH)
const SHELL = [
  "./",
  "./index.html",
  "./estate-story-20260926.json",
  "./estate-story-20260926.zh.json",
  "./estate-story-20260926.ja.json",
  "./credits/kellen-one-of-one-20260926.png",
  "./fonts.css",
  "./gate-preload.js",
  "./fonts/lora-latin-variable.woff2",
  "./favicon.svg",
  "./apple-touch-icon.png",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-maskable-512.png",
  "./manifest.webmanifest",
  "./snapshot/fx.json",
  "./snapshot/geo.json",
  "./snapshot/manifest.json",
  "./snapshot/status.json",
  "./snapshot/stocks.json",
  "./snapshot/weather.json",
  "./assets/index-CdOZsJxY.js",
  "./assets/rolldown-runtime-hePW80VL.js",
  "./assets/react-D0Ec-185.js",
  "./assets/idb-Bw8Vz8T8.js",
  "./assets/estate-integrity-DSAoa-Dz.js",
  "./assets/storage-BQlL5GDV.js",
  "./assets/estate-map-Bh0vX7rX.js",
  "./assets/prefs-CsyaKcQE.js",
  "./assets/lag-guard-UnPaIwkg.js",
  "./assets/use-fx-tier-CXWtt-Cv.js",
  "./assets/seasonal-art-DvkzNVKV.js",
  "./assets/fullscreen-CcoLpmTo.js",
  "./assets/focus-frame-sVNPGJ7y.js",
  "./assets/deck-CU42k3MN.js",
  "./assets/live-cards-CVBzaDvG.js",
  "./assets/live-DQsRLd_q.js",
  "./assets/popover-Cw51Vz19.js",
  "./assets/catalog-CF-jC7fI.js",
  "./assets/solitaire-6HBWCv0Z.js",
  "./assets/scores-Dlk0iM94.js",
  "./assets/build-info-CZxqHJt8.js",
  "./assets/tea-seal-Dx5keJNZ.js",
  "./assets/preload-helper-HclGiUj8.js",
  "./assets/door-transition-B3qEPZd1.js",
  "./assets/prefetch-BtNCDeko.js",
  "./assets/chunk-error-DrufujkD.js",
  "./assets/error-ledger-e4mlGXwq.js",
  "./assets/error-net-DGTxLR3j.js",
  "./assets/perf-trace-lIYLa8MR.js",
  "./assets/index-Ct-U9W_i.css",
  "./assets/corner-bl-DOalGHkc.svg",
  "./assets/corner-br-DECtH2Cd.svg",
  "./assets/corner-tl-BzMy2ihH.svg",
  "./assets/corner-tr-DWuKURBq.svg",
  "./assets/courtyard-7kFzMJ9R.js",
  "./assets/courtyard-BpoGdFvk.css",
  "./assets/estate-map-z8gv9Bjw.css",
  "./assets/fx-converter-DL-b7dAr.js",
  "./assets/fx-converter-mr6J6RWc.css",
  "./assets/game-sound-DtLTCPCI.js",
  "./assets/game-sound-switch-B4vmlSZx.js",
  "./assets/koku-BBSIOd4L.js",
  "./assets/pagoda-grid-CsFUHzJg.js",
  "./assets/pagoda-grid-Dg8_rbd5.css",
  "./assets/shelf-Bvr-IXlf.js",
  "./assets/speech-controls-Du-kQewd.js",
  "./assets/speech-prefs-BKDvDGgn.js",
  "./assets/table-head-YfScMEYJ.js",
  "./assets/tool-lang-CG_guNIL.js",
  "./assets/use-on-screen-DeliNmH0.js",
  "./assets/use-painted-DSFLHKBJ.js",
  "./assets/vine-h-D2f8jPMT.svg",
  "./assets/vine-v-Bwo7kXQE.svg",
  "./courtyard/posters/blossoms.webp",
  "./courtyard/posters/catch.webp",
  "./courtyard/posters/chess.webp",
  "./courtyard/posters/crystal.webp",
  "./courtyard/posters/descent.webp",
  "./courtyard/posters/fourinarow.webp",
  "./courtyard/posters/go.webp",
  "./courtyard/posters/koi.webp",
  "./courtyard/posters/konpira.webp",
  "./courtyard/posters/lantern.webp",
  "./courtyard/posters/mahjong.webp",
  "./courtyard/posters/matcha.webp",
  "./courtyard/posters/minigolf.webp",
  "./courtyard/posters/nonogram.webp",
  "./courtyard/posters/numbers.webp",
  "./courtyard/posters/pagoda.webp",
  "./courtyard/posters/pearl.webp",
  "./courtyard/posters/pinball.webp",
  "./courtyard/posters/reversi.webp",
  "./courtyard/posters/runner.webp",
  "./courtyard/posters/sakura.webp",
  "./courtyard/posters/seeds.webp",
  "./courtyard/posters/slide.webp",
  "./courtyard/posters/sokoban.webp",
  "./courtyard/posters/solitaire.webp",
  "./courtyard/posters/spirit.webp",
  "./courtyard/posters/sudoku.webp",
  "./courtyard/posters/sweeper.webp",
  "./courtyard/posters/terrarium.webp",
  "./courtyard/posters/tetris.webp",
  "./courtyard/posters/typing.webp",
  "./courtyard/posters/volley.webp",
  "./courtyard/posters/wordsearch.webp",
  "./courtyard/covers/catch-480.webp",
  "./courtyard/covers/catch-960.webp",
  "./courtyard/covers/chess-480.webp",
  "./courtyard/covers/chess-960.webp",
  "./courtyard/covers/crystal-480.webp",
  "./courtyard/covers/crystal-960.webp",
  "./courtyard/covers/go-480.webp",
  "./courtyard/covers/go-960.webp",
  "./courtyard/covers/koi-480.webp",
  "./courtyard/covers/koi-960.webp",
  "./courtyard/covers/konpira-480.webp",
  "./courtyard/covers/konpira-960.webp",
  "./courtyard/covers/lantern-480.webp",
  "./courtyard/covers/lantern-960.webp",
  "./courtyard/covers/mahjong-480.webp",
  "./courtyard/covers/mahjong-960.webp",
  "./courtyard/covers/matcha-480.webp",
  "./courtyard/covers/matcha-960.webp",
  "./courtyard/covers/nonogram-480.webp",
  "./courtyard/covers/nonogram-960.webp",
  "./courtyard/covers/numbers-480.webp",
  "./courtyard/covers/numbers-960.webp",
  "./courtyard/covers/pagoda-480.webp",
  "./courtyard/covers/pagoda-960.webp",
  "./courtyard/covers/runner-480.webp",
  "./courtyard/covers/runner-960.webp",
  "./courtyard/covers/sakura-480.webp",
  "./courtyard/covers/sakura-960.webp",
  "./courtyard/covers/slide-480.webp",
  "./courtyard/covers/slide-960.webp",
  "./courtyard/covers/sokoban-480.webp",
  "./courtyard/covers/sokoban-960.webp",
  "./courtyard/covers/solitaire-480.webp",
  "./courtyard/covers/solitaire-960.webp",
  "./courtyard/covers/sudoku-480.webp",
  "./courtyard/covers/sudoku-960.webp",
  "./courtyard/covers/sweeper-480.webp",
  "./courtyard/covers/sweeper-960.webp",
  "./courtyard/covers/terrarium-480.webp",
  "./courtyard/covers/terrarium-960.webp",
  "./courtyard/covers/tetris-480.webp",
  "./courtyard/covers/tetris-960.webp",
  "./courtyard/covers/typing-480.webp",
  "./courtyard/covers/typing-960.webp",
  "./courtyard/covers/volley-480.webp",
  "./courtyard/covers/volley-960.webp",
  "./art/catch/basket-catching.svg",
  "./art/catch/basket-idle.svg",
  "./art/catch/basket-miss.svg",
  "./art/catch/bloom.svg",
  "./art/catch/courtyard-day-1920w.webp",
  "./art/catch/danger-snow.svg",
  "./art/catch/gold.svg",
  "./art/catch/petal-18.svg",
  "./art/catch/petal-26.svg",
  "./art/catch/petal-32.svg",
  "./art/clouds/bank.webp",
  "./art/clouds/core.webp",
  "./art/clouds/left.webp",
  "./art/clouds/right.webp",
  "./art/clouds/top.webp",
  "./art/clouds/wisps.webp",
  "./art/covers/botanical-study-v1.webp",
  "./art/covers/moonlit-reflection-v1.webp",
  "./art/covers/path-to-the-peaks-v1.webp",
  "./art/covers/rainlit-archive-v2.webp",
  "./art/covers/sakura-workshop-v1.webp",
  "./art/covers/scholars-veranda-v1.webp",
  "./art/empty/draft-no-tasks.svg",
  "./art/empty/search-no-results.svg",
  "./art/empty/workspace-no-page.svg",
  "./art/map/pin-courtyard.svg",
  "./art/map/pin-door.svg",
  "./art/map/pin-hall.svg",
  "./art/map/pin-heron.svg",
  "./art/map/pin-tea.svg",
  "./art/map/pin-windchime.svg",
  "./art/map/state-here.svg",
  "./art/map/state-selected.svg",
  "./art/map/state-target.svg",
  "./art/sweeper/1.svg",
  "./art/sweeper/2.svg",
  "./art/sweeper/3.svg",
  "./art/sweeper/4.svg",
  "./art/sweeper/5.svg",
  "./art/sweeper/6.svg",
  "./art/sweeper/7.svg",
  "./art/sweeper/8.svg",
  "./art/sweeper/c.svg",
  "./art/sweeper/f.svg",
  "./art/sweeper/l.svg",
  "./art/sweeper/o.svg",
  "./art/sweeper/q.svg",
  "./art/sweeper/r.svg",
  "./art/sweeper/x.svg",
  "./art/tea/add-matcha.svg",
  "./art/tea/add-sencha.svg",
  "./art/tea/pour-shared.svg",
  "./art/tea/ready-matcha.svg",
  "./art/tea/ready-sencha.svg",
  "./art/tea/rest-matcha.svg",
  "./art/tea/rest-sencha.svg",
  "./art/tea/served-matcha.svg",
  "./art/tea/served-sencha.svg",
  "./art/tea/warm-shared.svg",
  "./estate/gate-morning-1920w.webp",
  "./estate/gate-afternoon-1920w.webp",
  "./estate/gate-evening-1920w.webp",
  "./estate/gate-night-1920w.webp",
  "./estate/door-morning-thumb.jpg",
  "./bible/kjv/index.json",
  "./doors/a-thumb.webp",
  "./doors/b-thumb.webp",
  "./doors/c-thumb.webp",
  "./doors/d-thumb.webp",
  "./doors/e-thumb.webp",
  "./doors/f-thumb.webp",
  "./doors/g-thumb.webp",
  "./doors/h-thumb.webp",
  "./doors/i-thumb.webp",
  "./fonts/inter-latin-400.woff2",
  "./fonts/inter-latin-500.woff2",
  "./fonts/inter-latin-700.woff2",
  "./fonts/jetbrains-mono-latin-400.woff2",
  "./fonts/jetbrains-mono-latin-600.woff2",
  "./fonts/jetbrains-mono-latin-700.woff2",
  "./fonts/klee-one-japanese-600-ui.woff2",
  "./fonts/lxgw-wenkai-screen-400-ui.woff2",
  "./fonts/noto-sans-jp-400-ui.woff2",
  "./fonts/noto-sans-jp-500-ui.woff2",
  "./fonts/noto-sans-jp-latin-400.woff2",
  "./fonts/noto-serif-jp-400-ui.woff2",
  "./fonts/noto-serif-jp-600-ui.woff2",
  "./fonts/noto-serif-jp-700-ui.woff2",
  "./fonts/noto-serif-jp-latin-400.woff2",
  "./fonts/noto-serif-sc-400-ui-borrowed.woff2",
  "./fonts/noto-serif-sc-400-ui.woff2",
  "./fonts/noto-serif-sc-700-ui-borrowed.woff2",
  "./fonts/noto-serif-sc-700-ui.woff2"
]
// The same list, asked the way the fetch handler asks it. Shell membership is
// tested on every request the worker sees, and an array answers by walking
// itself: with the room chunks precached the list is long enough that the walk
// is the first thing a navigation pays for. The array stays — the install loop
// reads it in order, and order is what makes a precache legible.
const SHELL_SET = new Set(SHELL)
// The same files with the SHA-256 of the bytes the build wrote (security
// benchmark item 7). SHELL stays a plain list beside it because the offline
// readiness card and verify:build read it out of this file as JSON.
const PRECACHE = [
  {
    "url": "./",
    "hash": "c5965bd352350a32b5e67cb0b7cc357150203fe9729f34e8e741c8f94a826f7b"
  },
  {
    "url": "./index.html",
    "hash": "c5965bd352350a32b5e67cb0b7cc357150203fe9729f34e8e741c8f94a826f7b"
  },
  {
    "url": "./estate-story-20260926.json",
    "hash": "fc6c7e1a1d6952b15fb415ef74434ec74bf75df704aeafdef97dd111c683b447"
  },
  {
    "url": "./estate-story-20260926.zh.json",
    "hash": "eb99c8413a4d03cb54883a3c266db1634423501771106ec62ee36a1c2f408dbd"
  },
  {
    "url": "./estate-story-20260926.ja.json",
    "hash": "bb1e66892f6459abae71cb0c0a2940bc6aa09cd4816da7a300cb8cce18e4286b"
  },
  {
    "url": "./credits/kellen-one-of-one-20260926.png",
    "hash": "090c4ddb7970dd1ec678890f9bd80176978f08661ed594892f9e2bf43c52dfcd"
  },
  {
    "url": "./fonts.css",
    "hash": "e2c918dfb1d3f706a79793e278e6b2bbf6753e9b46a0fe8695645da78900076d"
  },
  {
    "url": "./gate-preload.js",
    "hash": "c62b08f4e91ac6b3dbac7804de4fe43f9967f5ced68df792afd48003ad4abbf0"
  },
  {
    "url": "./fonts/lora-latin-variable.woff2",
    "hash": "7c514f026f03de1b0fc344c0c0f0df141fcf16b6f9ab672db191908ba740dab6"
  },
  {
    "url": "./favicon.svg",
    "hash": "413f6dad44ac92036bdcf74db47b438248e2a6382cf46e9fb6b660aaa118dd3b"
  },
  {
    "url": "./apple-touch-icon.png",
    "hash": "20afcf164d54185e307ed6e5fcfc161aff71456ed2dae30c67dce7fc9671bdaf"
  },
  {
    "url": "./icon-192.png",
    "hash": "475b1b8e20aaada9b20d4f4c75605eafb90e7d8bd9d30227743d0645d32920ed"
  },
  {
    "url": "./icon-512.png",
    "hash": "d7b222e073470fab318dd5d93e3b883050fdefdf9599998f0d90364fe96c21b7"
  },
  {
    "url": "./icon-maskable-512.png",
    "hash": "c16eb6a0258befebb34b45ce50d85f89935d6b5645f61a5d35306ed78a111be3"
  },
  {
    "url": "./manifest.webmanifest",
    "hash": "a33931ba4b3846679158ec51da353a79e42117a23f13afdfe3e33e6450a595bc"
  },
  {
    "url": "./snapshot/fx.json",
    "hash": "93e35ed78f86033154d27bc3a3ef191b6d3f2e0e5ee8062bd3ce5f7982e63450"
  },
  {
    "url": "./snapshot/geo.json",
    "hash": "c56ce5e8f35b2d1b651ba06de4cdc8a4b5c9c5d7eea1379a675e6f50ea26b670"
  },
  {
    "url": "./snapshot/manifest.json",
    "hash": "6640b458e37fa6783cfc965946c8f20bc57d7b1963b230cc4fedcf0e018beaa5"
  },
  {
    "url": "./snapshot/status.json",
    "hash": "335b5f03af8f0038b48fca3f4ed4a2cdc5fbf3fe0ae492f8f4e3e47729e7de41"
  },
  {
    "url": "./snapshot/stocks.json",
    "hash": "7fe64d6feafb9a35c953da0fe0f8b317505e3122ecce9594c4d007d37aa2170c"
  },
  {
    "url": "./snapshot/weather.json",
    "hash": "50ce70a27c9c6f3c8e32bf3cacdd14a1b27884db6c7bb3aba7bbd101f7b8902f"
  },
  {
    "url": "./assets/index-CdOZsJxY.js",
    "hash": "ea0ff99f9447aa4f2cfb146550c206f03ae75535a7f9972871f058dbeea3e44e"
  },
  {
    "url": "./assets/rolldown-runtime-hePW80VL.js",
    "hash": "580ad8c58061a4dde99bde0a56905e382f0568516ee2f5b84dbfb52085709021"
  },
  {
    "url": "./assets/react-D0Ec-185.js",
    "hash": "ce8893ab3fc497ab260a951fab2e349d928824cca435315bb53827218e88c39a"
  },
  {
    "url": "./assets/idb-Bw8Vz8T8.js",
    "hash": "6d269eb7328bacfe220ed21ec60127ca5a69957fc567b8c7e2a25c2e3e6c8cfb"
  },
  {
    "url": "./assets/estate-integrity-DSAoa-Dz.js",
    "hash": "582ceba77b1c5d2ad8aa2bc785efae889566377bdea0fb5d6a2d2a5bb9329650"
  },
  {
    "url": "./assets/storage-BQlL5GDV.js",
    "hash": "a4e5c6e044fc2b2e5ae29751578fad6b14d9b7dbd5f7f2d488b51797654a998b"
  },
  {
    "url": "./assets/estate-map-Bh0vX7rX.js",
    "hash": "691bc890f06071fa65a295073a70e13962214125cd4fadde041afefb08d67b48"
  },
  {
    "url": "./assets/prefs-CsyaKcQE.js",
    "hash": "e26694c29f7725da7f98e4352e3ff75219be4a89c2482506ee00aa1736df24c6"
  },
  {
    "url": "./assets/lag-guard-UnPaIwkg.js",
    "hash": "c7dd6ff04e575670a0d6226b480f6a449ed629fe3efbedd37f556d02cd19152c"
  },
  {
    "url": "./assets/use-fx-tier-CXWtt-Cv.js",
    "hash": "b26632933dab38475104d271cefd0b4edf6a14cf6d224a269db115b70720c8cf"
  },
  {
    "url": "./assets/seasonal-art-DvkzNVKV.js",
    "hash": "7d2bc2720171800a3b4d189b52461719d4e61785ebead69f85db67697030b5bd"
  },
  {
    "url": "./assets/fullscreen-CcoLpmTo.js",
    "hash": "a4dadb667b7f6271a982ea9fae014e94242e460eee214662cab305d8e4f03435"
  },
  {
    "url": "./assets/focus-frame-sVNPGJ7y.js",
    "hash": "90f2b0297644a2034279f03342e12b481ab44854cd0b22edf3d387cdabd6eae4"
  },
  {
    "url": "./assets/deck-CU42k3MN.js",
    "hash": "89f3d60faf4af86f73c18e78e228e802fdd44933b1cf8db21d207bdd746fd124"
  },
  {
    "url": "./assets/live-cards-CVBzaDvG.js",
    "hash": "ca87f0c10e574eb828d04469c96d8b662592382b570e08e8394380d885e8c5e0"
  },
  {
    "url": "./assets/live-DQsRLd_q.js",
    "hash": "0f752dd98a272cc688e9e067db02efd0f478f2079adf9aedfe114c774225b922"
  },
  {
    "url": "./assets/popover-Cw51Vz19.js",
    "hash": "29427e5bb86c5a0a094098f8c63c2524ab8e1ce4ae6d7558a2047797457b2f47"
  },
  {
    "url": "./assets/catalog-CF-jC7fI.js",
    "hash": "62428a6067b2ff18be5ef3ccc722a18b85ee09ea91722d076319377c0d491542"
  },
  {
    "url": "./assets/solitaire-6HBWCv0Z.js",
    "hash": "b340c208f483395ff3b53cc28e82f957541de1e4e2fc405ee9437e51afac9383"
  },
  {
    "url": "./assets/scores-Dlk0iM94.js",
    "hash": "946eb4ee6e20de8cc5f172f4b706092d2abe2890179ca70691a63ffddec0fca8"
  },
  {
    "url": "./assets/build-info-CZxqHJt8.js",
    "hash": "e209b1c070428a9d7dabfc1255d921fb9e09b6cc844325059dcffc2d53bd4854"
  },
  {
    "url": "./assets/tea-seal-Dx5keJNZ.js",
    "hash": "41a3d87b692632321b3c570fe1949524867ff32294fe772fef26a38be7074cab"
  },
  {
    "url": "./assets/preload-helper-HclGiUj8.js",
    "hash": "bba5840eec0028b00854bcd58fba80694d02d41e98417656424c05b26db7120c"
  },
  {
    "url": "./assets/door-transition-B3qEPZd1.js",
    "hash": "07da5b129766183a466c4cead67ef6bb2db617cd65c30f7684f09570af4f4b6b"
  },
  {
    "url": "./assets/prefetch-BtNCDeko.js",
    "hash": "4a82fc5af68db74c7746b777708b6ef7df52daa4f914592366f8e44e1e4a80e8"
  },
  {
    "url": "./assets/chunk-error-DrufujkD.js",
    "hash": "8d434b214b5faa63a387e8be4fb92ee893c1efb0087e0157c5f255d558f89dd3"
  },
  {
    "url": "./assets/error-ledger-e4mlGXwq.js",
    "hash": "26884f00a1357cbbc86cca38157c5469f75c6e28a4a51b473e7ee459837f4b7a"
  },
  {
    "url": "./assets/error-net-DGTxLR3j.js",
    "hash": "c767759fba1721685d0c85c1c751c6fe2f5c4aaeba9be99ccaa4ec49c6c35021"
  },
  {
    "url": "./assets/perf-trace-lIYLa8MR.js",
    "hash": "e8ee0bb2c1f96ac42099356178c4c31c5ede7596d03a584d7e7b1af67635f0a6"
  },
  {
    "url": "./assets/index-Ct-U9W_i.css",
    "hash": "3bca3854548fb3a86c9bba4d1162a568b608dccb3c061d24578486f5c71e9e83"
  },
  {
    "url": "./assets/corner-bl-DOalGHkc.svg",
    "hash": "71b81b8780f172d9dc5002b16332541dfa24b796d9ac7801b29b6b27e029b39a"
  },
  {
    "url": "./assets/corner-br-DECtH2Cd.svg",
    "hash": "13d7362dc1d2220f362456edf780692a2a8e8d2a6b7c6c7da508d7ff43dacbc2"
  },
  {
    "url": "./assets/corner-tl-BzMy2ihH.svg",
    "hash": "02c92db804628370121436f306b70be96bd4d418018091779355d5dcdf9b1495"
  },
  {
    "url": "./assets/corner-tr-DWuKURBq.svg",
    "hash": "2e9b67c2bfc30c72e816f1f6aed8e0e51c085edf8c79f9f33b0b96088f41add1"
  },
  {
    "url": "./assets/courtyard-7kFzMJ9R.js",
    "hash": "e5093ce2f36ca01ff49170c5ac8bdad1d8c6830b0c522de9868188192a2e872e"
  },
  {
    "url": "./assets/courtyard-BpoGdFvk.css",
    "hash": "834fcc08b2cc354d4cec22e4c064bfb9f639b96f619d05613e1146ac4c79facc"
  },
  {
    "url": "./assets/estate-map-z8gv9Bjw.css",
    "hash": "0fdce4485da74abdbc87ec42990904bfffb3c69b7418938eb05bdd12d03b9d6c"
  },
  {
    "url": "./assets/fx-converter-DL-b7dAr.js",
    "hash": "3572e88f26de2516fb7b9c67fbe1359933485f3e4273b8bf9d7fecac661b4f05"
  },
  {
    "url": "./assets/fx-converter-mr6J6RWc.css",
    "hash": "0a4b4c0c987ef4f83b4afa0d2bea1552af57f5f0b56218f0c7af6f2bcf026698"
  },
  {
    "url": "./assets/game-sound-DtLTCPCI.js",
    "hash": "bd6e4be5d8304974f065e0fd634b1eb239a7b35755e539cf9f61ee50dcdfe62c"
  },
  {
    "url": "./assets/game-sound-switch-B4vmlSZx.js",
    "hash": "087c91282e03dbc9a1c9ac9093c8b7c2cd8715b5c0d997cf76ebce465e225233"
  },
  {
    "url": "./assets/koku-BBSIOd4L.js",
    "hash": "54324dd3da16497c8ab620621bf296ce4b6a14ac2e88b1c307aedb3ba23c4584"
  },
  {
    "url": "./assets/pagoda-grid-CsFUHzJg.js",
    "hash": "cd43c62cea6db1a4ed0d5244d0dc684879a0087fab4647484c4f9f4446afe08e"
  },
  {
    "url": "./assets/pagoda-grid-Dg8_rbd5.css",
    "hash": "0e499eb4d37d18e57547a5e22f3dadb5b24c58010d7389acc7a0ae5340cfd194"
  },
  {
    "url": "./assets/shelf-Bvr-IXlf.js",
    "hash": "bda412b737d4ca917937b7412e98d9864fb0788673f273febee7c9b8f1ac01c7"
  },
  {
    "url": "./assets/speech-controls-Du-kQewd.js",
    "hash": "d4a2b1807058af5533bfbd350bf80bb920558c767b36329d0079838b3030eef0"
  },
  {
    "url": "./assets/speech-prefs-BKDvDGgn.js",
    "hash": "c9719381cc0e5dc4e314f446e8f9bb9db2ec2d21ad947314661e342eaa94cca4"
  },
  {
    "url": "./assets/table-head-YfScMEYJ.js",
    "hash": "36b379b0a5b80c123236b2a4f8631ec8154b1b3f704d32676603b80fb4f1de3d"
  },
  {
    "url": "./assets/tool-lang-CG_guNIL.js",
    "hash": "6ae8d1371bccf5d6ccd0f7d37e91f377500a5346a8e0542de8924114592f01b5"
  },
  {
    "url": "./assets/use-on-screen-DeliNmH0.js",
    "hash": "e1dff9bdd79e7903cb9e3fdf2f7103e50da0d18bf0aca1ba14a086dae378a5fb"
  },
  {
    "url": "./assets/use-painted-DSFLHKBJ.js",
    "hash": "340db8987b8fa76ff840e36a95b8d1ecf52496932a49d43a91ca4e8a0a208fc2"
  },
  {
    "url": "./assets/vine-h-D2f8jPMT.svg",
    "hash": "28bed0b74716da15e50b783d98578143b2bcdce4304c3e3dede558740ab70bb3"
  },
  {
    "url": "./assets/vine-v-Bwo7kXQE.svg",
    "hash": "6e8969f6fb61e3934e876b100ed638ae65d28f24e7ffb196f5f682b5aca5e89d"
  },
  {
    "url": "./courtyard/posters/blossoms.webp",
    "hash": "f190f93f80ff8aa265357f7c74b00f2483c143e96c2bd03601fd44294a074c93"
  },
  {
    "url": "./courtyard/posters/catch.webp",
    "hash": "424f2f7e28c445935078208351bb1940c87b5fb7810178740fa9caebdb4bbedf"
  },
  {
    "url": "./courtyard/posters/chess.webp",
    "hash": "25ce2b7a7651bdec0c20df91b4b2c923c97c7fc577dbfd6b4eadabe8c262cad6"
  },
  {
    "url": "./courtyard/posters/crystal.webp",
    "hash": "434fe60aa4145caf6fc09d1cd0fcea049897bb2fecfd04ff7325372353578d3b"
  },
  {
    "url": "./courtyard/posters/descent.webp",
    "hash": "6bca3da8a26aed1cd411cac77e0156d490e26995ee21b5072e57d68c17845145"
  },
  {
    "url": "./courtyard/posters/fourinarow.webp",
    "hash": "9be770a332a62ed5673e65e5b06faeab530a45c9de9355a7cab91165c754c32f"
  },
  {
    "url": "./courtyard/posters/go.webp",
    "hash": "c04662a6f413e15626abf940694ce837c0a0f57db0e50ce2db4e8062c701abf5"
  },
  {
    "url": "./courtyard/posters/koi.webp",
    "hash": "d3a40d92bce960f92481cf01ceb92dee90c08263edb754add9535dd240bf7bd8"
  },
  {
    "url": "./courtyard/posters/konpira.webp",
    "hash": "f68eff931736e98d522a4c338e91e2b5c3f36c5115d20849662486a5b8356503"
  },
  {
    "url": "./courtyard/posters/lantern.webp",
    "hash": "ff1a1d72e448c47517e1ca1c41be0d3a77f155c0e10957a9c73635567a05ef95"
  },
  {
    "url": "./courtyard/posters/mahjong.webp",
    "hash": "abfdd049fcd4a109fc180ecfa7894737c094214d4556ab0a15966e085194651d"
  },
  {
    "url": "./courtyard/posters/matcha.webp",
    "hash": "31f7327b75429bacb598e1f35b2e12b0b632a60ace30de9d133f0569ec4604f5"
  },
  {
    "url": "./courtyard/posters/minigolf.webp",
    "hash": "45a764737f6654893a973435011c708707ffd84f917419e1c9e7034017343251"
  },
  {
    "url": "./courtyard/posters/nonogram.webp",
    "hash": "7a19ab5c38dfef54954ae25a1d2678edcaecb38bd5d015541860e916c2bf88b1"
  },
  {
    "url": "./courtyard/posters/numbers.webp",
    "hash": "c65dea78748da20cbc5a6c7cf240f9a3a95ab4809cee17531eb50245b81251bb"
  },
  {
    "url": "./courtyard/posters/pagoda.webp",
    "hash": "b9708517c7d0bbd0a758853310858c70e224bbc8c2a9baaae5bee710126df0b5"
  },
  {
    "url": "./courtyard/posters/pearl.webp",
    "hash": "4191a81be9e18e138bf15e6ada84790db3842fedc9d3b09025d9f5adfbd271f6"
  },
  {
    "url": "./courtyard/posters/pinball.webp",
    "hash": "fca98ebdbe26d4658d86330ff7115d76542f6f91c51e295e193abde830c9b48f"
  },
  {
    "url": "./courtyard/posters/reversi.webp",
    "hash": "6bb95e9b97b45f628144ba308f11f3f5adfb2917e45fca9c67a961e4f77c4a10"
  },
  {
    "url": "./courtyard/posters/runner.webp",
    "hash": "89adf72244ce9f58da4d9b516f73453a5656843dfeec7d5ebaf970e4ade0708b"
  },
  {
    "url": "./courtyard/posters/sakura.webp",
    "hash": "2c33745d86d8a4d48316f7a87665b3adb147726ceaa8236d1098adf3c8acc466"
  },
  {
    "url": "./courtyard/posters/seeds.webp",
    "hash": "f551840d1b3c395ed54eaf9ebced1ffc2e3d370d13ba99ca9ab744976e4699a8"
  },
  {
    "url": "./courtyard/posters/slide.webp",
    "hash": "1f5ee8d9d64b715820f7926973d2d2db468938716e4b6b55179105705217e70c"
  },
  {
    "url": "./courtyard/posters/sokoban.webp",
    "hash": "e47906424970b008900c9786355d12aec7b466d937f7b4c18760d1b91963c8fb"
  },
  {
    "url": "./courtyard/posters/solitaire.webp",
    "hash": "a5aa71e1740563dabfa10992874b5d60660a5a10e2122f3778316f6f89007d91"
  },
  {
    "url": "./courtyard/posters/spirit.webp",
    "hash": "463a5ca3be621ecd9d76bfed8278bf5bc254ae2387a3f8d9f8d6474af91edaa6"
  },
  {
    "url": "./courtyard/posters/sudoku.webp",
    "hash": "01454d4e5542badf5d90678e5acc47b4ade960bff657c2a058fa5c66af550c1e"
  },
  {
    "url": "./courtyard/posters/sweeper.webp",
    "hash": "c4a308e9684b9f12f002957d3b9f8186615e7f44ee0e13a61c6b362f901c898b"
  },
  {
    "url": "./courtyard/posters/terrarium.webp",
    "hash": "1b55ab1956e9a03469a3bf72ce1569d390e9ffa5337a0692f59d0383df51b770"
  },
  {
    "url": "./courtyard/posters/tetris.webp",
    "hash": "9df2e5d852e0c155c33f0c5bb1aa5befe55d46561237196ba047e1ff4f84e4b7"
  },
  {
    "url": "./courtyard/posters/typing.webp",
    "hash": "f46877b454a725b67cdd88f507da2ad073eb6c8f0400a8ee45b0e4d3590c9e5c"
  },
  {
    "url": "./courtyard/posters/volley.webp",
    "hash": "ca0e5d7e647435695b1f38206aed574736e75ea41d961d098b23798a0920f0bc"
  },
  {
    "url": "./courtyard/posters/wordsearch.webp",
    "hash": "ed07543bff36c5a5f0afa458d687f492d35d5f808689fb1d938534aacbb2eafc"
  },
  {
    "url": "./courtyard/covers/catch-480.webp",
    "hash": "dc3f1341efb5966d97187db944b4b2f178b15ca603644cb0068728518dbba0e5"
  },
  {
    "url": "./courtyard/covers/catch-960.webp",
    "hash": "6932d45a0bcaddb6b6921bb9105a1e451a68296c5db159d8b97d3d4986688984"
  },
  {
    "url": "./courtyard/covers/chess-480.webp",
    "hash": "0b5cdaecec32340ac5031d376655e73896a9ecab2a0ed690c5f7b7f68a0b016b"
  },
  {
    "url": "./courtyard/covers/chess-960.webp",
    "hash": "d2199da302e3c6b0a9f397ba3b3fdc29dcd3e9ef42a07f5e1e28783cd0c86710"
  },
  {
    "url": "./courtyard/covers/crystal-480.webp",
    "hash": "5187125ced3e6d0087150cfad495a073e4b2d70351ef7f99babf32098cf397b6"
  },
  {
    "url": "./courtyard/covers/crystal-960.webp",
    "hash": "c715c82bb2adf0150b467df37b103b4f68732f8031e61eb2f3b874d5178d7d00"
  },
  {
    "url": "./courtyard/covers/go-480.webp",
    "hash": "2538d11304b3572cd9e7d22e71bc1379e9d57522f399035716196111d8bf4221"
  },
  {
    "url": "./courtyard/covers/go-960.webp",
    "hash": "1f16cc88fd43efdb6998192f3ac6bec29bdab72f0735ea7b17ce78478228fbad"
  },
  {
    "url": "./courtyard/covers/koi-480.webp",
    "hash": "9224281b44c76c492c30338ed982c7e57d2a49b9e255f2c9bc081fcfe3580156"
  },
  {
    "url": "./courtyard/covers/koi-960.webp",
    "hash": "081c9cdc7562e6d65f57f0038196bff9d1c0bab942ae9edbab4ccb5535376df0"
  },
  {
    "url": "./courtyard/covers/konpira-480.webp",
    "hash": "a16a9c9c7ff88dcb64294fad6ac11c8befc5c45b7b4090f004e26ba8fc591cfb"
  },
  {
    "url": "./courtyard/covers/konpira-960.webp",
    "hash": "236beb0f3346636c33856acb7f4dff75939398cb0d15a6807d893d9fc0d30f2a"
  },
  {
    "url": "./courtyard/covers/lantern-480.webp",
    "hash": "3574aadc03e165485dd2c34d3a4fa00903999dc9c3c7a938a73b65da4e8124a6"
  },
  {
    "url": "./courtyard/covers/lantern-960.webp",
    "hash": "de40fe5e33e87ba2100897a11038367dffe767316ea55b59d0166f53646fc95d"
  },
  {
    "url": "./courtyard/covers/mahjong-480.webp",
    "hash": "f636411fbe7bad5a3aef5e98eda199c07401fba1545b9937e1cb2ec10c8cfd20"
  },
  {
    "url": "./courtyard/covers/mahjong-960.webp",
    "hash": "0d4d1a50fe007dfd30f7047ac9b0efc3a53736e19b30a0e9383d3d19c5a349ef"
  },
  {
    "url": "./courtyard/covers/matcha-480.webp",
    "hash": "1fd7086aef31c11a19a5971bc136f601fe9dafafc6167231e7d0da63d89ee777"
  },
  {
    "url": "./courtyard/covers/matcha-960.webp",
    "hash": "f842f5734ffb919cc036e5a467e4efdcee369feaa4b0f132b36ea88fced37ec6"
  },
  {
    "url": "./courtyard/covers/nonogram-480.webp",
    "hash": "bbb0a2517f911d52881e5f4ecdf8781a37c8481dd54b974e5ed53f38ea957ad7"
  },
  {
    "url": "./courtyard/covers/nonogram-960.webp",
    "hash": "8381c0eb71965f0064b7f9b36ec0cbe359841b10b2beded81577247af10d9a2f"
  },
  {
    "url": "./courtyard/covers/numbers-480.webp",
    "hash": "06d65bccc55898acdbbd8d401e9985d8d2712bbc6399c2797ccd2fb664af1a11"
  },
  {
    "url": "./courtyard/covers/numbers-960.webp",
    "hash": "6a4b48b1d32d2367117e72b0b5384f402f83d44b6f99e1a7db027cfc4b48adff"
  },
  {
    "url": "./courtyard/covers/pagoda-480.webp",
    "hash": "d2dc9685360cec457bf84452ddb39d890d1643de18c5476299061b7d7923da9f"
  },
  {
    "url": "./courtyard/covers/pagoda-960.webp",
    "hash": "2681a62ec7231e244652204871554b2b90e7c8df44be68cbfa1bf56a5828a59f"
  },
  {
    "url": "./courtyard/covers/runner-480.webp",
    "hash": "e81d436e0b5ddfc3918055f4427a573230aa6bf45f0a81e42048c69e06b59866"
  },
  {
    "url": "./courtyard/covers/runner-960.webp",
    "hash": "c91749efc04b2242cfc06d181774b07fbf707cbdbee4289a4598a812169e1496"
  },
  {
    "url": "./courtyard/covers/sakura-480.webp",
    "hash": "411411c99536d00d31b6777c7d4343a5016eb69fc30a5811b22f02a6d4564fe2"
  },
  {
    "url": "./courtyard/covers/sakura-960.webp",
    "hash": "61bade339499fbcd1d12f3e8b4d027d1365b51f781f660c74fbefe9736466b83"
  },
  {
    "url": "./courtyard/covers/slide-480.webp",
    "hash": "0f63925295635aabf018e3668844c87bcd4b1f26e6cb8bd9182878de74a7afa3"
  },
  {
    "url": "./courtyard/covers/slide-960.webp",
    "hash": "df23531427f6dcf390f660c32d7592bfce5a460222794029df865e6c68614c14"
  },
  {
    "url": "./courtyard/covers/sokoban-480.webp",
    "hash": "d35d5939939dc864af8d20807254d024a58556416d402f9bbb0b02cd57b3f9ba"
  },
  {
    "url": "./courtyard/covers/sokoban-960.webp",
    "hash": "51da034abe7adc2f3b383e04870d086a3860bc3a9c3d0beb1cb9344b846b28e1"
  },
  {
    "url": "./courtyard/covers/solitaire-480.webp",
    "hash": "aa08977fd0d63ceb7b48b75a0ac78b1bb85d0b08255d4bbefd7b70606c6df642"
  },
  {
    "url": "./courtyard/covers/solitaire-960.webp",
    "hash": "aff2e1f1fdb4c68ebe2db9eceed9e3fbbdade8c7ca936bd441c27c5dfc982aa1"
  },
  {
    "url": "./courtyard/covers/sudoku-480.webp",
    "hash": "883b74c52c14b703136088d8499425f8387d70189cff7b5a79be14bb0c832526"
  },
  {
    "url": "./courtyard/covers/sudoku-960.webp",
    "hash": "3c06d5912867185840fbe83dcadf0f189cdb44f92597825cebe83c7f4eefb613"
  },
  {
    "url": "./courtyard/covers/sweeper-480.webp",
    "hash": "6be79db8794502cc0fa6bdaa4a3c4b99ce593751d12aafa3408755dc046fdf94"
  },
  {
    "url": "./courtyard/covers/sweeper-960.webp",
    "hash": "4a94beb37d3505e39f1267dd675ed5b84e9ea0a30b3442719a68eb7938bbbc77"
  },
  {
    "url": "./courtyard/covers/terrarium-480.webp",
    "hash": "79d7b2d6e657cc288f8f75515f91dc641c434ab7c30958a31e312c15a42bda36"
  },
  {
    "url": "./courtyard/covers/terrarium-960.webp",
    "hash": "9d88bb95bfbebfa3ce5bd463a2eb2be15cf4956c610f12de218e90a348367d93"
  },
  {
    "url": "./courtyard/covers/tetris-480.webp",
    "hash": "050dae111951a6fd3becb894f1f7560f0bbdcb1ed9eb17195bcc43ebe84b10fe"
  },
  {
    "url": "./courtyard/covers/tetris-960.webp",
    "hash": "569a34906b6a3fe590282c57e53d7e03a56aba327bd3f4d820456cdc07a11f0a"
  },
  {
    "url": "./courtyard/covers/typing-480.webp",
    "hash": "d0374c70bd133b80fef797a6b442d7c13372bebba673978331849938e4a35503"
  },
  {
    "url": "./courtyard/covers/typing-960.webp",
    "hash": "7f50b7037aa749517e9af2353a2d08819b6f80d6fe416ec506454fd2e3918c08"
  },
  {
    "url": "./courtyard/covers/volley-480.webp",
    "hash": "43cd22a3cdbf8b76f4d933634b7caee02cc7ed85522011f13dc9fff68fdcd9ae"
  },
  {
    "url": "./courtyard/covers/volley-960.webp",
    "hash": "53559cf10b4521b247abf1bd2ab33646502298ef392507eca24e4a2d10ae81ac"
  },
  {
    "url": "./art/catch/basket-catching.svg",
    "hash": "9c285fdf1fafc86070596695da4035ca544db5d95bec9ef86a0fc6c151eead22"
  },
  {
    "url": "./art/catch/basket-idle.svg",
    "hash": "98f1eac15dc873531766813b74f5ce1bbd664cb34fe29e61935a6117867bee4c"
  },
  {
    "url": "./art/catch/basket-miss.svg",
    "hash": "ab6e93d8bb653cb636f678d047e76fe86cc410d507308bdc6a33c6dfd8005c95"
  },
  {
    "url": "./art/catch/bloom.svg",
    "hash": "496cc016d6f9e7b019f8209e4086e27924fc212e140fa3a8926fde620b796765"
  },
  {
    "url": "./art/catch/courtyard-day-1920w.webp",
    "hash": "cc2d3974cd8e7e812a853ec876440cdedbd2cdb85dfbc0039a5704eb16a1c3a4"
  },
  {
    "url": "./art/catch/danger-snow.svg",
    "hash": "dace42ee4c9e71346492c4ef40764df2fc5b858df0f2761e9c56ba224cad0c08"
  },
  {
    "url": "./art/catch/gold.svg",
    "hash": "b62c8fab2355de2d5ac6eb5e2f42001a38c440f979390d5dccf18222e0a930cc"
  },
  {
    "url": "./art/catch/petal-18.svg",
    "hash": "9b9ce8b4d1cd1022e5ff3459cd016eecf76797b3f42260ffd1ab422d469dbd1b"
  },
  {
    "url": "./art/catch/petal-26.svg",
    "hash": "d42d2617f6fcdd4e9c4be855eba6f5353b4d3c16311a24cae4992b2c435ea79e"
  },
  {
    "url": "./art/catch/petal-32.svg",
    "hash": "24e9a8dbb2b9c3e9b09d2ca10c56c9ac2851e1e93145bf19ca371a81f93b573b"
  },
  {
    "url": "./art/clouds/bank.webp",
    "hash": "f93ffee948612a004aa959fdd595e0d5c9f8e948ee5468cdb307b09331d435d6"
  },
  {
    "url": "./art/clouds/core.webp",
    "hash": "a3f5b18243e48531117c22d8d4e60da0f5d48cfdc201a01b085e338ffc81cf12"
  },
  {
    "url": "./art/clouds/left.webp",
    "hash": "3476e558c30c37715ec203ae6d4694b6ac2eed20eec492591150d2dc98e3ab9e"
  },
  {
    "url": "./art/clouds/right.webp",
    "hash": "8c29d423bc6afb6ed5daf1e10b98bd7cc62178c2b1d7dd99a77ed41c90c69d6f"
  },
  {
    "url": "./art/clouds/top.webp",
    "hash": "68fd015bbc42a28a4b4a09bd0a0123d1dd7f47137e296fe4d9a12f5451d0975e"
  },
  {
    "url": "./art/clouds/wisps.webp",
    "hash": "d8eaffa0835767e83e462786ea2e9473253b67560b333e8ca2416d77b0b87ea3"
  },
  {
    "url": "./art/covers/botanical-study-v1.webp",
    "hash": "eb06bda9ef71fb45c78854e57c5bc79c65b908ee47b0b6577d8b50367b458b29"
  },
  {
    "url": "./art/covers/moonlit-reflection-v1.webp",
    "hash": "3499a46e1172881168312bae831acc990d6b0df77cde88eda6d1a48e6deaa135"
  },
  {
    "url": "./art/covers/path-to-the-peaks-v1.webp",
    "hash": "7c10b78a98381dd34f31f87cee90bba2856ba8c9525b71b618b6e8be5589d984"
  },
  {
    "url": "./art/covers/rainlit-archive-v2.webp",
    "hash": "a25d0eff14d2a013294998ff1d41e98755e914a1cee03553ad51712dee6b2dbf"
  },
  {
    "url": "./art/covers/sakura-workshop-v1.webp",
    "hash": "05a05a08aadfe87493b660761dd953922b2b545bfb0f6a8257e5ce9929c452b6"
  },
  {
    "url": "./art/covers/scholars-veranda-v1.webp",
    "hash": "1de7d8735d995bc3fc45a567bdaf0f827e03eabc558a5c81b78b347cfe29eddb"
  },
  {
    "url": "./art/empty/draft-no-tasks.svg",
    "hash": "73d9f744949a1e9d8cf09ef20e600f78acfcbdf1a0d5015410bbcfdb13b6ecbe"
  },
  {
    "url": "./art/empty/search-no-results.svg",
    "hash": "ccfac087d6320062e46ae14d45b07c0540116ddc43a4b1a747a2fbe93f68e90e"
  },
  {
    "url": "./art/empty/workspace-no-page.svg",
    "hash": "9cfb18765bf4ae04a57ace90352e6a56b63ac98fcb8c6a38e28d8e03f29ab8bf"
  },
  {
    "url": "./art/map/pin-courtyard.svg",
    "hash": "7716f5e7374fcfc2234704bd9cdd3f6e10a753011985b3177bdea461c35755e8"
  },
  {
    "url": "./art/map/pin-door.svg",
    "hash": "3e90f5278b08157f8ff8453be45c701bec6eec08fe163369f10b9b617e2cadf3"
  },
  {
    "url": "./art/map/pin-hall.svg",
    "hash": "21eb54d514fe9903ff3524a716ae46cce0848871b2e21029a4ab832341ebc268"
  },
  {
    "url": "./art/map/pin-heron.svg",
    "hash": "6dc8f21d7856cf97ec2d297c21bbae49bfafab4df620f80428291c4ea3bb0f16"
  },
  {
    "url": "./art/map/pin-tea.svg",
    "hash": "efd1b95e26576c3c7c7da1a2bcd7ffc542e69192f02c475811bb32b0d76462ce"
  },
  {
    "url": "./art/map/pin-windchime.svg",
    "hash": "89eb7715a5db275ff855d2634b923fab2669aa274d534e5631f79a9ef8e15446"
  },
  {
    "url": "./art/map/state-here.svg",
    "hash": "c17719d11661a40d352a11b6e8c6e47d7ce3bc545318de98e21c494ea3f2f831"
  },
  {
    "url": "./art/map/state-selected.svg",
    "hash": "5a7c93aad534044116993984bbb92a411620014054f7fcd8117ddb026a2d71a9"
  },
  {
    "url": "./art/map/state-target.svg",
    "hash": "a86d775abfc6d0afb671dae8c4ac4e11be6a0044c59f917a7b9fc0537c15264d"
  },
  {
    "url": "./art/sweeper/1.svg",
    "hash": "c494de509a005aab9769a3f28b1a580707b46ab0f164a01233a4952ba25854dc"
  },
  {
    "url": "./art/sweeper/2.svg",
    "hash": "7b01915b4e3cc31bbd03242246620386d0f806c09de468fc7d7af0168a7d4805"
  },
  {
    "url": "./art/sweeper/3.svg",
    "hash": "229685a5e42c9f213c057b2a0387c7e52c3f0f7cc518dd10ea58820fab988f01"
  },
  {
    "url": "./art/sweeper/4.svg",
    "hash": "cb5015ee6cc8d5cfaa9b16dd1ee8f63212970d2632c001a77ec64d3e7a70dce4"
  },
  {
    "url": "./art/sweeper/5.svg",
    "hash": "59012d4a55eee2a53df3b1db9aa8528f2922c2dc35991298185b92a57f5f96d8"
  },
  {
    "url": "./art/sweeper/6.svg",
    "hash": "9e3daf5564c5b0087d57874d0f320c9db70dc4fc9f83eedd83b3249cc4376f35"
  },
  {
    "url": "./art/sweeper/7.svg",
    "hash": "e3779de94eb600a409e47ac824b00fef39e3302bf285a13281776b51a149cd68"
  },
  {
    "url": "./art/sweeper/8.svg",
    "hash": "956deb70510243e9a42376aa9e4a52582d22cc8a998d98191eebd42c1007a17a"
  },
  {
    "url": "./art/sweeper/c.svg",
    "hash": "fea50c41062c042e014174edd86e51192c7b72b01a7ba1288d89cd6a57e932f2"
  },
  {
    "url": "./art/sweeper/f.svg",
    "hash": "4aecf3d27a7dae70bc8e665da25bb5bbdd7d3693b6356330653f2e31a9c40084"
  },
  {
    "url": "./art/sweeper/l.svg",
    "hash": "94a993a0b7e2d565bf435674e4b13d68fc24550d9cf26106eaec115c1de6deb8"
  },
  {
    "url": "./art/sweeper/o.svg",
    "hash": "cf6d3cdefc3ea54f6346aefa9b7c4df54985608dec342266494ad393f60e0c09"
  },
  {
    "url": "./art/sweeper/q.svg",
    "hash": "9376ced6251c3c320c667a92ba6dd281c593969812b8bee8e2b1537c3077d55b"
  },
  {
    "url": "./art/sweeper/r.svg",
    "hash": "14f6ba16a128bd66e3dbe1f6033008206b70bd67d8c718c4ca4447047e5e5da5"
  },
  {
    "url": "./art/sweeper/x.svg",
    "hash": "96225afa1dcd55f8cee618d1ca342396968114d2e81c36507249acfad1f6861a"
  },
  {
    "url": "./art/tea/add-matcha.svg",
    "hash": "7c8e50010500eef782a0a719d329079a46000720a87debdbfd02452b5a8d161f"
  },
  {
    "url": "./art/tea/add-sencha.svg",
    "hash": "5568edce1c351025f2c725e56c8cebe2bc18d52455e01d78a11c20be12e9db45"
  },
  {
    "url": "./art/tea/pour-shared.svg",
    "hash": "f6630047f87e4ef924c01a09f009caf158b84e0854b6185c1eebfcc0958ca89e"
  },
  {
    "url": "./art/tea/ready-matcha.svg",
    "hash": "5bd261eba0f2de6f863acc53227dbef0d5d5cf14940fa4f43c10a6415d793a6a"
  },
  {
    "url": "./art/tea/ready-sencha.svg",
    "hash": "1f49ef17a530b6f2fffa374750e80c8e2965e695fa632d6042407735fd335ca3"
  },
  {
    "url": "./art/tea/rest-matcha.svg",
    "hash": "f3c2201a9a1b4e394c434aae418004a3396b54463c45cda04968cc514c38cff5"
  },
  {
    "url": "./art/tea/rest-sencha.svg",
    "hash": "820d4bbec5ead3f2dbfe38182e1916cc60a4050352d610bea6f880d19e0de0b5"
  },
  {
    "url": "./art/tea/served-matcha.svg",
    "hash": "f04b2aa050b3e4888fea52adfbccf350f72919774e23f79269706f8e62d7bd06"
  },
  {
    "url": "./art/tea/served-sencha.svg",
    "hash": "f57cc502408ea2b767764b598cdb8be3a9f1c535e7362c254a1d31c5a3fad24d"
  },
  {
    "url": "./art/tea/warm-shared.svg",
    "hash": "1194e1f33f4d8fbc84562984b1f576ff252cd53e9bae59ae0d7f9947e00cface"
  },
  {
    "url": "./estate/gate-morning-1920w.webp",
    "hash": "cec8b74968994c78192002297b1226746e3f3ea2ec8ec9c49f3f02c8e742dbba"
  },
  {
    "url": "./estate/gate-afternoon-1920w.webp",
    "hash": "7692f65dc68e09e5cbd953803bec7d34bf33901a87a31a68c7b68bb1ee0639dd"
  },
  {
    "url": "./estate/gate-evening-1920w.webp",
    "hash": "a567e72fd29a8f9bf852a12036d0a6b77f640f4db5d8a02c3b2411adba9e76e2"
  },
  {
    "url": "./estate/gate-night-1920w.webp",
    "hash": "48557d17fc630669de2e9203b077698563d2fc89339958cc10a4290a400398ef"
  },
  {
    "url": "./estate/door-morning-thumb.jpg",
    "hash": "3ba9c2877cbcbe9b8d9b10d5d43787310b8f783d5c17f015d5135225add8cc9f"
  },
  {
    "url": "./bible/kjv/index.json",
    "hash": "54049d500b8add73aa09da0dac07110f00e184fd70d5a645210540a8c06b3b01"
  },
  {
    "url": "./doors/a-thumb.webp",
    "hash": "d2cee95819da477435c3b6ce23ee97a015f30dc0e7756b04536d919b5b7f6392"
  },
  {
    "url": "./doors/b-thumb.webp",
    "hash": "2700d10d5d15000976ad47dfa280a7003804f2b59bc4062301eafd92c121a444"
  },
  {
    "url": "./doors/c-thumb.webp",
    "hash": "b66f6d54f143690f628ad3f195b5fc6f34d86df47562fffdd33e771e7c422b1b"
  },
  {
    "url": "./doors/d-thumb.webp",
    "hash": "94eb97463abb9dd4108bc010284145d55bb800b22619d62cc835b25c8912a09d"
  },
  {
    "url": "./doors/e-thumb.webp",
    "hash": "ec6d772eda1d7dae6db8168f5a2852250364e9f6e82fc98798ef327ad758cb1b"
  },
  {
    "url": "./doors/f-thumb.webp",
    "hash": "636e5219d462fe0de5ffe16ecf791698b7614dbb2da22fb913655c59088849a0"
  },
  {
    "url": "./doors/g-thumb.webp",
    "hash": "a84a2ca9a99838290d1f0bcc06ad286b9ac4b59d4d1de568cba1a8df37778dc7"
  },
  {
    "url": "./doors/h-thumb.webp",
    "hash": "f02cdde9b16e5b9296db209b2c642db3af0c97b6b8d605ce23f60b0270140eb5"
  },
  {
    "url": "./doors/i-thumb.webp",
    "hash": "c7f3927127b4fbf0bbd8969fc7faa0949b671d9e78544d645ecae8a80684026d"
  },
  {
    "url": "./fonts/inter-latin-400.woff2",
    "hash": "8909904ab6c872eb994093482a88a28eca2cd95912d7b6fecd72103b0dc07edc"
  },
  {
    "url": "./fonts/inter-latin-500.woff2",
    "hash": "f3779f1efccc4bdcdf9c0a02ab95bf6bd092ed09c48c08cedc725889edd1d19f"
  },
  {
    "url": "./fonts/inter-latin-700.woff2",
    "hash": "6f56409fd3d64bb85f7d070bce20749db2d66b6d63cec586cc22d1c761be2491"
  },
  {
    "url": "./fonts/jetbrains-mono-latin-400.woff2",
    "hash": "14425ba9c695763c1547f48a206b7aa60350a33ae23de09f0407877f3fcd89eb"
  },
  {
    "url": "./fonts/jetbrains-mono-latin-600.woff2",
    "hash": "400c6bfda18d5d14acad1c15d6dcb9f8e13c015e7286317e0b9a482539bef147"
  },
  {
    "url": "./fonts/jetbrains-mono-latin-700.woff2",
    "hash": "d0d4e818808f2a0ba39b2b09d1989366f63494e295f003c7ef436697378507e8"
  },
  {
    "url": "./fonts/klee-one-japanese-600-ui.woff2",
    "hash": "14afeec733a13cf6ef9f9f7e160aeb95a76906f2465fdeb1b3025d697a57c7e0"
  },
  {
    "url": "./fonts/lxgw-wenkai-screen-400-ui.woff2",
    "hash": "6f051cd4e70c975a30a4325c91489aa84d936120a082617b6a65e049a7f97940"
  },
  {
    "url": "./fonts/noto-sans-jp-400-ui.woff2",
    "hash": "e0f61596957cda44d05392c38543e2952be3abae77fa9a550de3f9f8ae091324"
  },
  {
    "url": "./fonts/noto-sans-jp-500-ui.woff2",
    "hash": "f0aeb1ac51dd104babe7886d24295d9af3c39076c4f1b2534f6e26d4d2aac65c"
  },
  {
    "url": "./fonts/noto-sans-jp-latin-400.woff2",
    "hash": "7f1d26777c9a28442745485c9e617d9b89c3f479aa69bd80448f6612e2c8e168"
  },
  {
    "url": "./fonts/noto-serif-jp-400-ui.woff2",
    "hash": "de7b4884d36ba6af54470dcd0122e029cde394db40ee8b84330cbf0e8645bf72"
  },
  {
    "url": "./fonts/noto-serif-jp-600-ui.woff2",
    "hash": "34760dcf3fa184b00b9dd97b051072857898ebf32fb02dd434986b5a29c004db"
  },
  {
    "url": "./fonts/noto-serif-jp-700-ui.woff2",
    "hash": "5338363d221da3662f89fd9878da9760fb0e8dc8a91c1bcaeb1c2d5c8cd63c60"
  },
  {
    "url": "./fonts/noto-serif-jp-latin-400.woff2",
    "hash": "9354cb0c699384284e426c18695f86c54afa334d09ab1a3c4b077a61fa063c97"
  },
  {
    "url": "./fonts/noto-serif-sc-400-ui-borrowed.woff2",
    "hash": "a3d460126d0a4a3f0d556283c5f125e968f341203461a2312c09d25e4041ddcd"
  },
  {
    "url": "./fonts/noto-serif-sc-400-ui.woff2",
    "hash": "2ec70f49d274807a9801de5d5ebd48bed77b2ff2a6017eca70898923659aa86f"
  },
  {
    "url": "./fonts/noto-serif-sc-700-ui-borrowed.woff2",
    "hash": "f1a7e2e36748fe38b9e120ac78cab03f4f755cd8e424c48eebe34d649157f6bc"
  },
  {
    "url": "./fonts/noto-serif-sc-700-ui.woff2",
    "hash": "10bbdf9cceed7651d79c6b8b941668d3d267daa7f09452dc0ee56aae596ebcd8"
  }
]
const PRECACHE_HASH = new Map(PRECACHE.map((entry) => [entry.url, entry.hash]))
// Paths served stale-while-revalidate: same names across builds, so refresh behind the cache.
// 2026-10-02 integration fix: `koi-bespoke/` (the bespoke koi atlases) joins `koi/` under
// the same rule; the prefix is matched up to its slash, so `koi` alone never covered it and
// the atlases never reached the runtime cache for offline play.
const STALE_OK = /^\.\/(fonts|estate|bible|koi|art|quotes|assistants|voice|doors|koi-bespoke)\//
// The sealed tea room's own files, which sit at the root rather than in a
// directory of their own and so match no prefix above: eight encrypted hero
// pictures, the seal's key file and the portrait, 14 MB in all. Without a rule
// a visitor who installed the estate downloaded the whole room and still met a
// lock that could not open without a network. Stale-while-revalidate out of
// RUNTIME, never precached — 14 MB on install is not an install.
const TEA_OK = /^\.\/(ayaka-tea-hero[^/]*\.webp\.enc|tea-seal\.json|ayaka-portrait\.jpg)$/
// Everything the runtime cache holds, and therefore everything the trim measures.
function runtimeOk(rel) {
  return STALE_OK.test(rel) || TEA_OK.test(rel)
}
// Paths never cached: the estate's own live endpoints, which must not go stale.
const LIVE = /^\.\/api\//
// The bundled captures: network first (they may be re-captured between builds),
// but answered from the precache when the network is not there at all.
const SNAPSHOT = /^\.\/snapshot\//
// A navigation waits this long for the network before the precached shell answers.
const NAV_PATIENCE_MS = 3000
// How many revalidated files the cache keeps. The paintings and the 66 tea
// clips are megabytes each; without a ceiling the cache grows for ever.
const STALE_CAP = 240
// And how many *bytes* it keeps. A count alone is not a ceiling: 240 entries of
// paintings and tea clips is hundreds of megabytes on a visitor's device, which
// is not a cache, it is a download. Sizes come from the cached responses'
// own `content-length`; an entry that does not declare one is assumed to be
// this many bytes rather than free, so an unlabelled file cannot hide.
const STALE_BYTE_CAP = 120 * 1024 * 1024
const ASSUMED_BYTES = 256 * 1024
const TRIM_EVERY_MS = 30000
// How many cached entries a trim measures at once. One await per slice instead
// of one per entry; small enough that a deep cache is not read whole.
const TRIM_SLICE = 24
let trimmedAt = 0
// What the device has actually granted. STALE_BYTE_CAP above is the estate's
// own ceiling and it is a fixed number on every device: a phone with a gigabyte
// left and a phone with forty megabytes left were both told to keep 120 MB of
// paintings and tea clips. The browser answers that by evicting the origin's
// storage whole — which costs the visitor the precached shell, the record book
// and the saved games at once, and offline costs them the estate. The cache
// therefore keeps half of what the device says it may have, or the estate's own
// ceiling, whichever is the smaller.
//
// Read once per worker life, off the fetch path: `estimate()` is a round trip
// and a quota does not move while a worker is alive. Where it does not exist —
// Safari before 17, a private window — the constant stands, as it did.
let grantedCap = 0
async function byteCap() {
  if (grantedCap) return grantedCap
  grantedCap = STALE_BYTE_CAP
  try {
    const store = navigator.storage
    if (store && typeof store.estimate === 'function') {
      const quota = Number((await store.estimate()).quota)
      if (Number.isFinite(quota) && quota > 0) grantedCap = Math.min(STALE_BYTE_CAP, Math.floor(quota / 2))
    }
  } catch {
    // An estimate that throws is no grant at all: the estate's own ceiling stands.
  }
  return grantedCap
}

// A precache miss must not kill the install.
//
// `addAll` is one transaction: a single 404, a redirect, or one file a proxy
// or an extension refuses rejects the whole thing, and the worker never
// installs at all — so an estate that would have worked offline apart from one
// missing icon works offline not at all, and silently, because nothing on the
// page ever learns the install failed. Each URL is added on its own, what fails
// is counted and named in the console, and the shell that did arrive is kept.
// `verify:build` still holds every SHELL entry to a real file on disk, so a
// miss here is a fault worth reading about, not a state to tolerate quietly.
//
// A file that arrives but is not the file the build wrote is another matter.
// Each response is hashed with SHA-256 and compared with PRECACHE; one mismatch
// throws out of waitUntil, so the install fails and the worker already active
// keeps serving the build it verified. A miss is a file that is not there; a
// mismatch is a file that is not ours, and that is never cached as the shell.
class PrecacheIntegrityError extends Error {}
function hexOf(buffer) {
  return Array.from(new Uint8Array(buffer), (b) => b.toString(16).padStart(2, '0')).join('')
}
async function precacheOne(cache, url) {
  const want = PRECACHE_HASH.get(url)
  if (!want) {
    await cache.add(url)
    return
  }
  // Revalidated, never read from the HTTP cache: a name-stable file (fonts.css,
  // index.html) held over from the previous build would fail its hash.
  const response = await fetch(url, { cache: 'no-cache' })
  if (!response.ok) throw new TypeError('Request failed: ' + url + ' (' + response.status + ')')
  const copy = response.clone()
  const got = hexOf(await crypto.subtle.digest('SHA-256', await response.arrayBuffer()))
  if (got !== want) throw new PrecacheIntegrityError(url)
  await cache.put(url, copy)
}
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_STORE)
    const missed = []
    for (const url of SHELL) {
      try {
        await precacheOne(cache, url)
      } catch (err) {
        if (err instanceof PrecacheIntegrityError) {
          if (typeof console !== 'undefined') console.error('[ayaka] precache integrity check failed for ' + url + ': install aborted')
          throw err
        }
        missed.push(url)
      }
    }
    if (missed.length && typeof console !== 'undefined') {
      console.warn('[ayaka] ' + missed.length + ' of ' + SHELL.length + ' precache entries did not arrive: ' + missed.join(', '))
    }
  })())
})

// A new worker waits instead of taking over a tab that is already open: swapping
// the shell under a visitor mid-session serves them half of one build and half of
// the next. The page offers a reload and posts this message when it is taken.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
  if (event.data && event.data.type === 'ADOPT_ART' && Array.isArray(event.data.urls)) {
    event.waitUntil(adoptArt(event.data.urls))
  }
})

// Notifications, phase 1: a reminder shown through registration.showNotification
// is clicked here, not in the page. An estate window inside this worker's scope
// is focused and told which entry to open, so it walks there by its own
// navigation; with none open, the reminder's own address is opened — only if it
// sits inside this scope, so a stored URL can never send the visitor elsewhere.
// Nothing here schedules or pushes: phase 1 has no push and no closed-app alarm.
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const data = event.notification.data || {}
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true })
    for (const client of windows) {
      if (!new URL(client.url).pathname.startsWith(SCOPE_PATH)) continue
      client.postMessage({ type: 'ayaka-notify-open', mailId: typeof data.mailId === 'string' ? data.mailId : null, dest: data.dest || null })
      return client.focus()
    }
    let target = new URL('./', self.location.href)
    try {
      const asked = new URL(String(data.url || ''), self.location.href)
      if (asked.origin === self.location.origin && asked.pathname.startsWith(SCOPE_PATH)) target = asked
    } catch {
      /* a malformed address opens the estate's front page */
    }
    return self.clients.openWindow(target.href)
  })())
})
// A first visit paints before this worker controls the page, so the paintings
// it showed never passed through here — and WebKit then serves them from its
// memory cache for the rest of the visit, so they never will. Offline after
// that first visit, the room the visitor was just in had no painting. The page
// posts what it has already shown once this worker claims it; each one the
// runtime cache does not hold yet is fetched and put, under the same rules and
// trim as a painting fetched through the worker. Only this deployment's own
// art paths are taken, at most ADOPT_MAX of them, one at a time.
const ADOPT_MAX = 64
async function adoptArt(urls) {
  const cache = await caches.open(RUNTIME_STORE)
  let taken = 0
  for (const href of urls.slice(0, ADOPT_MAX)) {
    let url
    try {
      url = new URL(href, self.location.href)
    } catch (e) {
      continue
    }
    const rel = relative(url)
    if (rel === null || SHELL_SET.has(rel) || !STALE_OK.test(rel) || LIVE.test(rel)) continue
    if (await cache.match(url.href, { ignoreVary: true })) continue
    try {
      const res = await fetch(url.href)
      if (res.ok) {
        await cache.put(url.href, res)
        taken++
      }
    } catch (e) {
      // offline already, or the host refused: nothing to adopt, nothing lost
    }
  }
  if (taken) await trim(cache).catch(() => {})
  return taken
}

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // The browser may start the navigation request while the worker is still
    // booting, so a cold start costs nothing.
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable().catch(() => {})
    }
    const keys = await caches.keys()
    // Only *this deployment's* caches. caches.keys() is origin-wide: the other
    // projects published on this host keep their caches in the same place, and
    // so does the estate's other deployment at the other path on this very
    // origin. OWNED ends in the "~" that scopeKey can never produce, so this
    // predicate cannot reach past its own namespace.
    //
    // Legacy, un-namespaced "ayaka-…" caches written before c103a are left
    // alone rather than swept: while one path has updated and the other has
    // not, deleting them would take the offline shell out from under the
    // deployment still using them — exactly the bug being fixed. They belong to
    // no namespace, are never opened again, and are left to the quota manager.
    const mine = keys.filter((k) => k.startsWith(OWNED) && k !== SHELL_STORE && k !== RUNTIME_STORE)
    await Promise.all(mine.map((k) => caches.delete(k)))
    await self.clients.claim()
  })())
})

// The path of a request relative to the worker's own directory, as "./x/y".
function relative(url) {
  const base = new URL('./', self.location.href)
  if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return null
  return './' + url.pathname.slice(base.pathname.length)
}

// Read from this cache by name, never the origin-wide caches.match: a hashed
// name from another project on the same host could answer for one of ours.
//
// `ignoreVary`: a hashed asset is the same bytes for every request. A host
// that answers with `Vary: Origin` (vite preview does; so do many CORS-aware
// CDNs) made the precached copy unmatchable for `import()`, which sends an
// Origin header the install-time fetch did not — so offline, every lazy chunk
// (Settings, the games) failed although it sat in this very cache. Found by
// the Playwright offline journey (e2e/combinations.spec.ts).
async function cacheFirst(req) {
  const cache = await caches.open(SHELL_STORE)
  const hit = await cache.match(req, { ignoreVary: true })
  if (hit) return hit
  const res = await fetch(req)
  if (res.ok) cache.put(req, res.clone()).catch(() => {})
  return res
}

// The bundled captures: the network's answer is always preferred, and the
// precached copy stands in when there is no network or the host answers badly.
// This is what makes `?offline=1` true offline rather than "offline, provided
// the network is up".
async function freshFirst(req) {
  const cache = await caches.open(SHELL_STORE)
  try {
    const res = await fetch(req)
    if (res && res.ok) {
      cache.put(req, res.clone()).catch(() => {})
      return res
    }
    const hit = await cache.match(req)
    return hit || res
  } catch (err) {
    const hit = await cache.match(req)
    if (hit) return hit
    throw err
  }
}

// A metered or very slow connection pays for every background refresh, so on one
// the cached copy answers alone and nothing is fetched behind it.
function thrifty() {
  const link = navigator.connection
  if (!link) return false
  return Boolean(link.saveData) || link.effectiveType === 'slow-2g' || link.effectiveType === '2g'
}

// Keeps the runtime cache under STALE_CAP entries, oldest first
// (cache.keys() answers in insertion order). Throttled, and always off the path
// the visitor is waiting on.
async function trim(cache) {
  const now = Date.now()
  if (now - trimmedAt < TRIM_EVERY_MS) return
  // Stamped before the first await, so the trims a burst of puts asks for are
  // one trim and not a queue of them.
  trimmedAt = now
  const [cap, keys] = await Promise.all([byteCap(), cache.keys()])
  const stale = keys.filter((r) => {
    const rel = relative(new URL(r.url))
    return rel !== null && runtimeOk(rel)
  })
  if (stale.length <= 1) return
  // Newest first, keeping entries until either ceiling is reached; everything
  // older than the cut is dropped. One entry always survives, however large it
  // declares itself, so a single oversized file cannot empty the cache.
  //
  // The sizes are read a sliceful at a time rather than one entry after
  // another: `cache.match` is a storage round trip, and awaiting up to
  // STALE_CAP of them in a row made a trim as long as the cache is deep. A
  // slice is one await for TRIM_SLICE lookups, the walk inside it is still
  // newest-first and stops at the same entry the sequential walk stopped at,
  // and the ceilings are reached within a slice of where they were before —
  // so at most TRIM_SLICE-1 lookups are paid for and not used.
  let bytes = 0
  let keep = 0
  let full = false
  for (let end = stale.length; end > 0 && keep < STALE_CAP && !full; end -= TRIM_SLICE) {
    const start = Math.max(0, end - TRIM_SLICE)
    const hits = await Promise.all(stale.slice(start, end).map((r) => cache.match(r)))
    for (let i = hits.length - 1; i >= 0 && keep < STALE_CAP; i -= 1) {
      const hit = hits[i]
      const declared = hit && hit.headers ? Number(hit.headers.get('content-length')) : 0
      const size = Number.isFinite(declared) && declared > 0 ? declared : ASSUMED_BYTES
      if (keep > 0 && bytes + size > cap) {
        full = true
        break
      }
      bytes += size
      keep += 1
    }
  }
  if (keep >= stale.length) return
  await Promise.all(stale.slice(0, stale.length - keep).map((r) => cache.delete(r)))
}

// `which` is RUNTIME_STORE for the name-stable files and SHELL_STORE for the few shell
// entries that are not hashed (`fonts.css`, the manifest, the favicon): those
// were precached with this build and must still answer offline from it.
//
// `opts` is handed straight to `cache.match`. The sealed tea files are asked for
// with a `?b=<commit>` stamp (`src/lib/tea-seal.ts`), so a stamped ask after a
// deploy would miss a perfectly good cached copy — and store a second one beside
// it — unless the lookup ignores the query. Nothing else here needs that: the
// rest of the runtime half is asked for by bare path.
async function staleWhileRevalidate(req, which, opts) {
  const cache = await caches.open(which)
  // `ignoreVary` for the reason `cacheFirst` gives: a static file is the same
  // bytes whoever asks, and a host's `Vary: Origin` must not make an adopted
  // painting (stored from the worker's own request) miss an <img>'s request.
  const hit = await cache.match(req, { ignoreVary: true, ...opts })
  if (hit && thrifty()) return hit
  // Stored under a name with the query stripped whenever the lookup ignores it:
  // otherwise every deploy's stamp would leave another copy of a 2 MB picture
  // beside the last one, and the trim would spend the whole ceiling on one room.
  const key = opts && opts.ignoreSearch ? new URL(req.url).origin + new URL(req.url).pathname : req
  const refresh = fetch(req).then((res) => {
    if (res.ok) cache.put(key, res.clone()).then(() => (which === RUNTIME_STORE ? trim(cache) : undefined)).catch(() => {})
    return res
  })
  if (hit) {
    refresh.catch(() => {})
    return hit
  }
  return refresh.catch(async (error) => {
    // A larger viewport can select an uncached full painting while offline.
    // Keep its exact scene/crop/format from this deployment's smaller cache;
    // never store those lower-resolution bytes under the full-size key.
    // 2026-10-01: a load the page itself abandoned (an image whose source was
    // swapped mid-flight, as Firefox does when a full-screen change flips the
    // painting's orientation) is answered quietly; nobody is waiting for it,
    // and a rejected respondWith is logged by Firefox as a page error.
    if (error && error.name === 'AbortError') return new Response('', { status: 499, statusText: 'Abandoned' })
    const url = new URL(req.url)
    const rel = relative(url)
    // The seasonal paintings live one folder down (./estate/seasons/) and keep a 640w rung.
    if (which === RUNTIME_STORE && /^\.\/estate\/(?:[^/]+\/)?[^/]+\.(webp|jpe?g)$/i.test(rel) && !/-\d+w\./i.test(rel)) {
      const shell = await caches.open(SHELL_STORE)
      for (const width of [1920, 1280, 640]) {
        const rung = new URL(url.href)
        rung.pathname = rung.pathname.replace(/(\.[^.]+)$/, '-' + width + 'w$1')
        const lower = await shell.match(rung.href) || await cache.match(rung.href)
        if (lower && lower.ok) return lower
      }
    }
    // 2026-10-02: a painting that cannot be had from anywhere is answered with a
    // network-error response rather than a rejected respondWith. The page sees
    // the same thing either way (the <img> errors, a fetch() rejects), but
    // Firefox logs a rejected respondWith as a page error ("A ServiceWorker
    // intercepted the request and encountered an unexpected error"), and it
    // rejects with a plain NetworkError, not an AbortError, when the page drops
    // an image mid-load during a Focus painting swap. Nobody is waiting for
    // that answer; it is not an error of the estate's.
    // 3 October 2026: the same for every request this path serves, not only a
    // runtime image. The full e2e gate, with four workers, saw Firefox log that
    // page error for three font files on a reload mid-game and for a seasonal
    // painting asked for during a full-screen swap: shell-store asks and
    // non-image asks were still thrown. A network-error response is what the
    // page sees in both cases; only the browser's console differs.
    return Response.error()
  })
}

async function shellFirst(event) {
  const cache = await caches.open(SHELL_STORE)
  const cached = await cache.match('./index.html')
  const network = (async () => {
    const preloaded = await event.preloadResponse
    const res = preloaded || (await fetch(event.request))
    /*
      The answer is deliberately *not* written back into SHELL_STORE, which is stamped
      with this build's commit and holds this build's shell, precached on
      install; within a build there is nothing about `./index.html` to refresh.
      After a deploy, though, this handler still belongs to the old worker (a new
      one waits), so the page it would store is the *new* index.html, naming
      hashed `assets/…` URLs that are in neither this cache nor, once the deploy
      settles, reachable offline. The next slow or offline navigation was then
      answered with a shell whose scripts could not be found: a blank estate,
      which is the exact half-old, half-new mixture the waiting-worker flow
      exists to prevent.
    */
    return res
  })()
  /*
    A host that answers at all can still answer badly: GitHub Pages hands out its
    own 404 page for a deep link into the estate. That is not the estate, so the
    precached shell answers instead whenever the response is not ok — not only
    when the fetch throws.
  */
  const answer = network
    .then((res) => ((res && res.ok) || !cached ? res : cached))
    .catch((err) => {
      if (cached) return cached
      throw err
    })
  if (!cached) return answer
  /*
    And a captive portal answers neither way: it holds the connection open and
    the navigation hangs on a blank tab. The shell is on disk, so after
    NAV_PATIENCE_MS it is served and the estate opens.
  */
  let timer = 0
  const patience = new Promise((resolve) => {
    timer = setTimeout(() => resolve(cached), NAV_PATIENCE_MS)
  })
  return Promise.race([answer, patience]).finally(() => clearTimeout(timer))
}

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  const rel = relative(url)
  if (rel === null) return
  if (LIVE.test(rel)) return
  if (SNAPSHOT.test(rel)) {
    event.respondWith(freshFirst(req))
    return
  }
  if (req.mode === 'navigate') {
    event.respondWith(shellFirst(event))
    return
  }
  if (rel.startsWith('./assets/')) {
    event.respondWith(cacheFirst(req))
    return
  }
  // Shell membership is asked first. The two tests overlap — `./fonts/` is a
  // STALE_OK prefix and the precached `fonts.css` and its woff2 sit under it —
  // and STALE_OK winning meant a file that was *put in this build's cache at
  // install* was looked for in the runtime cache instead, which offline is
  // empty on a first paint. The estate then opened in a fallback face. What was
  // precached answers from where it was precached.
  if (SHELL_SET.has(rel)) {
    event.respondWith(staleWhileRevalidate(req, SHELL_STORE))
    return
  }
  if (STALE_OK.test(rel)) {
    event.respondWith(staleWhileRevalidate(req, RUNTIME_STORE))
    return
  }
  if (TEA_OK.test(rel)) {
    event.respondWith(staleWhileRevalidate(req, RUNTIME_STORE, { ignoreSearch: true }))
  }
})
